USE [LinksDB20]
GO
--'1885','01','101','MUM','PDG','','30/12/2009','BP','G100276','CENTRAL BANK OF INDIA, BOMBAY [G_ACCOUNT]','1520000','','150000','DSFDSAFD','4000.00','PDG ','1885','127.0.0.1',''
ALTER PROCEDURE [dbo].[USP_ACC_BRBPCRCPCE_INSERT_NG]
--DECLARE
	@CMPID VARCHAR(5),
	@CMPCODE VARCHAR(2), 
	@CITYCODE1 VARCHAR(3),
	@CITYCODE VARCHAR(3),
	@USERNAME VARCHAR(20),
	@ENTRYNO AS VARCHAR(15),
	@ENTRYDT AS VARCHAR(10),
	@STATUS AS VARCHAR(3),
	@OURBANK AS VARCHAR(7),
	@OURBANKNM AS VARCHAR(1000),
	@CHEQUETYPE AS VARCHAR(7),
	@CHEQUENO AS VARCHAR(7),
	@CHEQUEDT AS VARCHAR(10),
	@BANK AS VARCHAR(50),
	@NARRATION AS NVARCHAR(120),
	@ACTUALAMOUNT AS NVARCHAR(50),
	@VGUID NVARCHAR(200),
	@MAKER_ID NVARCHAR(50),
	@MAKER_IP NVARCHAR(50),
	@NOTOVERFLAG VARCHAR(1),
	@ACTION  NVARCHAR(20),
	@PayeeName NVARCHAR(110),
	@BANKREFNO VARCHAR(30)
	
AS /*
--'USP_ACC_BRBPCRCPCE_INSERT','1885','01','101','MUM','PDG','','28/01/2010','RCP','','','','','','','8500.00','PDG','1885','127.0.0.1','','UPDATE',''
--'1885','01','101','MUM','PDG','','30/12/2009','BP','G100276','CENTRAL BANK OF INDIA, BOMBAY [G_ACCOUNT]','1520000','','150000','DSFDSAFD','4000.00','PDG ','1885','127.0.0.1',''
SELECT	@CMPID = '1885',
	@CMPCODE = '01',
	@CITYCODE1  = '101',
	@CITYCODE  = 'MUM',
	@USERNAME  = 'PDG',
	@ENTRYNO  = '',
	@ENTRYDT  = '28/01/2010',
	@STATUS  = 'RCP',
	@OURBANK  = '',
	@OURBANKNM  = '',
	@CHEQUENO  = '',
	@CHEQUEDT  ='',
	@BANK  = '',
	@NARRATION  = 'DSFDSAFD',
	@ACTUALAMOUNT  = '8500.00',
	@VGUID  = 'PDG ',
	@MAKER_ID  = '1885',
	@MAKER_IP  = '127.0.0.1',
	@NOTOVERFLAG  = '',
	@ACTION='UPDATE',
	@PayeeName=''
--*/
--BEGIN		
	DECLARE @INT INT 
	DECLARE @INTCHK INT
	DECLARE @ERROR INT
	DECLARE @TEMPSTRING NVARCHAR(4000)
	DECLARE @TEMP NVARCHAR(4000)
	DECLARE @COUNT INT
	DECLARE @INNERTEMP NVARCHAR(500)
	DECLARE @INNERCOUNT INT


	--FOR USER TRACK		
	DECLARE @COLNAMES AS NVARCHAR(4000)
			,@ORGINALCOLDATA NVARCHAR(4000)
			,@NEWCOLDATA NVARCHAR (4000)
			,@TEMP1 NVARCHAR(1000)
			,@TEMPCASHBOOKID AS INT
			,@TRACKID AS INTEGER
			,@MODE AS VARCHAR(10)
	---USERTRACK


	SET XACT_ABORT ON --<< FIX: abort + rollback everything on any runtime error

	IF(@STATUS = 'BP') SET @CHEQUEDT = @ENTRYDT

	--IF((@STATUS = 'BP' OR @STATUS = 'BR' OR @STATUS = 'CC') AND (len(@CHEQUENO) > 0 and @CHEQUENO <> 'PO'))
	IF(@STATUS = 'B11P')
	BEGIN 
		--select ''	
		DECLARE @ENTRYNO1 NVARCHAR(15)
		SELECT @ENTRYNO1 = ENTRYNO FROM ACC_BANK WHERE  CITYCODE = @CITYCODE AND CMPCODE = @CMPCODE AND STATUS=@STATUS AND CHEQUENO=@CHEQUENO 
		--IF (LEN(ISNULL(@ENTRYNO1, '')) = 15)
		--BEGIN
		--	--RETURN '103#Cheque No. ' + @CHEQUENO + ' already exist for this entry no. ' + @ENTRYNO1 
			--SELECT '103#Cheque No. ' + @CHEQUENO + ' already exist for this entry no. ' + @ENTRYNO1 [STATUS]
		--END
	END -- END OF CHEQ VALIDATION
	ELSE
	BEGIN

		--<< FIX: Bank Payment Request (CC) must have child lines - block master insert when temp is empty
		IF @STATUS = 'CC' AND (SELECT COUNT(*) FROM ACC_BANKDTLS_TMP WHERE VGUID = @VGUID AND ISDELETED <> 'Y') = 0
		BEGIN
			SELECT '103#No detail records found!' [STATUS],
			       'Child records are missing. Please re-enter the details and submit again.' [STATUSTEXT]
			RETURN
		END

		---GENERATIOG  NEW BILLNO STARTS HERE


		DECLARE	 @PRECODE AS VARCHAR(15)
				,@TEMPSQL AS NVARCHAR(1000)
				,@LASTCODE AS VARCHAR(15)
				,@INTCNT AS INT
				,@RIGHTNUM AS VARCHAR(10)
				,@VOUCHERTYPE AS VARCHAR(1)

		IF(@STATUS = 'BR') 
			SET @VOUCHERTYPE = '1'
		ELSE IF(@STATUS = 'BP') 
			SET @VOUCHERTYPE = '2'
		ELSE IF(@STATUS = 'CP') 
			SET @VOUCHERTYPE = '8'
		ELSE IF(@STATUS = 'CR') 
			SET @VOUCHERTYPE = '7'
		ELSE IF(@STATUS = 'CE') 
			SET @VOUCHERTYPE = '9'	
		ELSE IF(@STATUS = 'CC') 
			SET @VOUCHERTYPE = 'R'	
		ELSE IF(@STATUS = 'RCP') 
			SET @VOUCHERTYPE = 'P'


		SET @PRECODE =	@CMPCODE 
						+ @CITYCODE1 
						+ SUBSTRING(@ENTRYDT, 9, 2)
						+ SUBSTRING(@ENTRYDT, 4, 2) 
						+ SUBSTRING(@ENTRYDT, 1, 2)  
						+ @VOUCHERTYPE
		/* ************************************************ max code ***************************************************/
		EXEC [dbo].[USP_ACC_BRBPCRCPCE_INSERT_CODE] @STATUS,@PRECODE,  @ENTRYNO OUTPUT
/*
		DECLARE @MAXCODE NVARCHAR(15)
		SET @MAXCODE = ''

		IF(@STATUS = 'BR') 
		BEGIN
			BEGIN TRANSACTION;
				SELECT @MAXCODE = MAX(ENTRYNO) FROM ACC_BANK_CODE_BR WHERE PRECODE = @PRECODE
				SET @ENTRYNO = [dbo].[fn_ACC_BRBPCRCPCE_MAXCODE](@PRECODE,@MAXCODE)
				IF @MAXCODE IS NULL
					INSERT INTO ACC_BANK_CODE_BR (PRECODE, ENTRYNO) VALUES (@PRECODE,@ENTRYNO)
				ELSE
					UPDATE ACC_BANK_CODE_BR SET ENTRYNO = @ENTRYNO WHERE PRECODE = @PRECODE
			COMMIT TRANSACTION;
		END
		ELSE IF(@STATUS = 'BP') 
		BEGIN
			BEGIN TRANSACTION;
				SELECT @MAXCODE = MAX(ENTRYNO) FROM ACC_BANK_CODE_BP WHERE PRECODE = @PRECODE
				SET @ENTRYNO = [dbo].[fn_ACC_BRBPCRCPCE_MAXCODE](@PRECODE,@MAXCODE)
				INSERT INTO ACC_BANK_CODE_BP (PRECODE, ENTRYNO) VALUES (@PRECODE,@ENTRYNO)
			COMMIT TRANSACTION;
		END
		ELSE IF(@STATUS = 'CP') 
		BEGIN
			BEGIN TRANSACTION;
				SELECT @MAXCODE = MAX(ENTRYNO) FROM ACC_BANK_CODE_CP WHERE PRECODE = @PRECODE
				SET @ENTRYNO = [dbo].[fn_ACC_BRBPCRCPCE_MAXCODE](@PRECODE,@MAXCODE)
				INSERT INTO ACC_BANK_CODE_CP (PRECODE, ENTRYNO) VALUES (@PRECODE,@ENTRYNO)
			COMMIT TRANSACTION;
		END
		ELSE IF(@STATUS = 'CR') 
		BEGIN
			BEGIN TRANSACTION;
				SELECT @MAXCODE = MAX(ENTRYNO) FROM ACC_BANK_CODE_CR WHERE PRECODE = @PRECODE
				SET @ENTRYNO = [dbo].[fn_ACC_BRBPCRCPCE_MAXCODE](@PRECODE,@MAXCODE)
				INSERT INTO ACC_BANK_CODE_CR (PRECODE, ENTRYNO) VALUES (@PRECODE,@ENTRYNO)
			COMMIT TRANSACTION;
		END
		ELSE IF(@STATUS = 'CE') 
		BEGIN
			BEGIN TRANSACTION;
				SELECT @MAXCODE = MAX(ENTRYNO) FROM ACC_BANK_CODE_CE WHERE PRECODE = @PRECODE
				SET @ENTRYNO = [dbo].[fn_ACC_BRBPCRCPCE_MAXCODE](@PRECODE,@MAXCODE)
				INSERT INTO ACC_BANK_CODE_CE (PRECODE, ENTRYNO) VALUES (@PRECODE,@ENTRYNO)
			COMMIT TRANSACTION;
		END
		ELSE IF(@STATUS = 'CC') 
		BEGIN
			BEGIN TRANSACTION;
				SELECT @MAXCODE = MAX(ENTRYNO) FROM ACC_BANK_CODE_CC WHERE PRECODE = @PRECODE
				SET @ENTRYNO = [dbo].[fn_ACC_BRBPCRCPCE_MAXCODE](@PRECODE,@MAXCODE)
				INSERT INTO ACC_BANK_CODE_CC (PRECODE, ENTRYNO) VALUES (@PRECODE,@ENTRYNO)
			COMMIT TRANSACTION;
		END
*/
		/* ************************************************ max code ***************************************************/
		--BEGIN TRANSACTION
		--	SELECT @ENTRYNO=[dbo].[fn_ACC_BANK_CODE](@PRECODE)  
		--	-- IF @@ERROR != 0 GOTO ERROR_HANDLER

		--	INSERT INTO ACC_BANK_CODE (ENTRYNO,PRECODE) VALUES (@ENTRYNO,@PRECODE)
		--	-- IF @@ERROR != 0 GOTO ERROR_HANDLER
		--COMMIT TRANSACTION
		--SET @ENTRYNO = ''
		--EXEC [DBO].[USP_ACC_BRBPCRCPCE_INSERT_CODE] @PRECODE,@STATUS, @ENTRYNO
		
		DECLARE @PK_ID INT,
				@_TBLNAME NVARCHAR(50)
		SET @PK_ID = 0

		IF(@STATUS = 'CC') 
		BEGIN
			SET @_TBLNAME = 'ACC_BANK_CMP'
			SELECT @PK_ID = ID FROM ACC_BANK_CMP WHERE ENTRYNO = @ENTRYNO
		END
		ELSE IF(@STATUS = 'RCP') 
		BEGIN
			SET @_TBLNAME = 'ACC_BANK_RCP'
			SELECT @PK_ID = ID FROM acc_bank_RCP WHERE ENTRYNO = @ENTRYNO
		END
		ELSE
		BEGIN
			SET @_TBLNAME = 'ACC_BANK'
			SELECT @PK_ID = ID FROM ACC_BANK WHERE ENTRYNO = @ENTRYNO
		END
			
		IF ISNULL(@PK_ID,0) = 0
		BEGIN
			BEGIN TRANSACTION --<< FIX: master + details + amount must save atomically
			IF(@STATUS = 'CC') 
			BEGIN
				INSERT INTO ACC_BANK_CMP
				(
					ENTRYNO,
					ENTRYDT,
					[STATUS],
					BANK,
					CHEQUETYPE,
					CHEQUENO,
					CHEQUEDT,
					OURBANK,
					NARRATION,
					CITYCODE,
					CMPCODE,
					ENTMM,
					ENTYR,
					ENTDD,
					ENTNO,
					EXPENSE,
					USERNAME,
					CMPID,
					ACTUALAMOUNT,
					NOTOVERFLAG,
					PayeeName,
					ComputerisedCheque,
					CHKPRINTAUTHORITY
				)
				VALUES
				(   
					@ENTRYNO,
					@ENTRYDT,
					'BP',
					@BANK,
					@CHEQUETYPE,--NULL,
					@CHEQUENO,
					@CHEQUEDT,
					@OURBANK,
					@NARRATION,
					@CITYCODE,
					@CMPCODE,
					SUBSTRING(@ENTRYDT, 4, 2),
					SUBSTRING(@ENTRYDT, 9, 2),
					SUBSTRING(@ENTRYDT, 1, 2),
					SUBSTRING(@ENTRYNO, 13,3),
					NULL,
					@USERNAME,
					@CMPID,
					@ACTUALAMOUNT,
					@NOTOVERFLAG,
					@PayeeName,
					1,
					0
				)
				-- IF @@ERROR != 0 GOTO ERROR_HANDLER
				
				SET @TEMPCASHBOOKID = IDENT_CURRENT('ACC_BANK_CMP')  --@@IDENTITY
			END
			ELSE IF (@STATUS = 'RCP')
			BEGIN
				
				INSERT INTO ACC_BANK_RCP
				(
					ENTRYNO,
					ENTRYDT,
					[STATUS],
					BANK,
					CHEQUETYPE,
					CHEQUENO,
					CHEQUEDT,
					OURBANK,
					NARRATION,
					CITYCODE,
					CMPCODE,
					ENTMM,
					ENTYR,
					ENTDD,
					ENTNO,
					EXPENSE,
					USERNAME,
					CMPID,
					ACTUALAMOUNT,
					AuthorisationStatus,
					REQUESTEDON
				)
				VALUES
				(   
					@ENTRYNO,
					@ENTRYDT,
					@STATUS,
					@CHEQUETYPE,--NULL,
					@BANK,
					@CHEQUENO,
					@CHEQUEDT,
					@OURBANK,
					@NARRATION,
					@CITYCODE,
					@CMPCODE,
					SUBSTRING(@ENTRYDT, 4, 2),
					SUBSTRING(@ENTRYDT, 9, 2),
					SUBSTRING(@ENTRYDT, 1, 2),
					SUBSTRING(@ENTRYNO, 13,3),
					NULL,
					@USERNAME,
					@CMPID,
					@ACTUALAMOUNT,
					'U', 
					CONVERT(VARCHAR,GETDATE(),100)
				)
				-- IF @@ERROR != 0 GOTO ERROR_HANDLER	
				
				SET @TEMPCASHBOOKID = IDENT_CURRENT('ACC_BANK_RCP')  --@@IDENTITY
			END
			ELSE
			BEGIN
				INSERT INTO ACC_BANK
				(
					ENTRYNO,
					ENTRYDT,
					[STATUS],
					BANK,
					CHEQUETYPE,
					CHEQUENO,
					CHEQUEDT,
					OURBANK,
					NARRATION,
					CITYCODE,
					CMPCODE,
					ENTMM,
					ENTYR,
					ENTDD,
					ENTNO,
					EXPENSE,
					USERNAME,
					CMPID,
					ACTUALAMOUNT,
					NOTOVERFLAG,
					BANKREFNO
				)
				VALUES
				(   
					@ENTRYNO,
					@ENTRYDT,
					@STATUS,
					@BANK,
					@CHEQUETYPE,--NULL,
					@CHEQUENO,
					@CHEQUEDT,
					@OURBANK,
					@NARRATION,
					@CITYCODE,
					@CMPCODE,
					SUBSTRING(@ENTRYDT, 4, 2),
					SUBSTRING(@ENTRYDT, 9, 2),
					SUBSTRING(@ENTRYDT, 1, 2),
					SUBSTRING(@ENTRYNO, 13,3),
					NULL,
					@USERNAME,
					@CMPID,
					@ACTUALAMOUNT,
					@NOTOVERFLAG,
					@BANKREFNO
				)
				-- IF @@ERROR != 0 GOTO ERROR_HANDLER	
				
				SET @TEMPCASHBOOKID = IDENT_CURRENT('ACC_BANK')  --@@IDENTITY
			END

			
			
			--USERTRACK STARTS HERE 
			SET @COLNAMES = 'ENTRYNO|ENTRYDT|STATUS|BANK|CHEQUETYPE|CHEQUENO|CHEQUEDT|OURBANK|NARRATION|CITYCODE|CMPCODE|PayeeName'
			SET @ORGINALCOLDATA = @ENTRYNO + '|' + @ENTRYDT + '|' + @STATUS + '|' + @BANK + '|' + @CHEQUETYPE + '|' + @CHEQUENO + '|' + @CHEQUEDT + '|' + @OURBANK  + '|' + @NARRATION + '|' +  @CITYCODE + '|' + @CMPCODE + '|' + @PayeeName

			INSERT INTO TBL_USERTRACK( USERID, [DATETIME], MODE, TABLENAME, COLUMNNAME, ORIGINALDATA, MODIFIEDDATA, RECORDID,CODE)
			VALUES (@CMPID, GETDATE(), 'ADD', @_TBLNAME, @COLNAMES, @ORGINALCOLDATA, '', @TEMPCASHBOOKID, @ENTRYNO)
			SET @TRACKID = @@IDENTITY
			-- IF @@ERROR != 0 GOTO ERROR_HANDLER

			EXEC DBO.[USP_ACC_BRBPCRCPCE_INSERT_DTLS_NG] @ENTRYNO,@STATUS,@VGUID,@TRACKID,@MAKER_ID,@MAKER_IP, @ACTION
			
			/* START UPDATE MASTER TABLE ACTUAL AMOUNT WITH SUM OF [AMOUNT-DEDUCTION] FROM CHILD TABLE */
			IF @STATUS = 'CC'
			BEGIN
				UPDATE	ACC_BANK_CMP
				SET		ACTUALAMOUNT = CONVERT(DECIMAL (18,2), ISNULL(((SELECT ISNULL(CONVERT (DECIMAL (18,2), SUM(CONVERT(FLOAT,ACC_BANKDTLS_CMP.AMOUNT))),0)  - ISNULL(CONVERT (DECIMAL (18,2), SUM(CONVERT(FLOAT,ACC_BANKDTLS_CMP.DEDUCTION))),0) 
				FROM	ACC_BANKDTLS_CMP WHERE ACC_BANKDTLS_CMP.ENTRYNO = ACC_BANK_CMP.ENTRYNO)),0))
				WHERE	ENTRYNO = @ENTRYNO
			END
			ELSE IF @STATUS = 'RCP'
			BEGIN
				UPDATE	ACC_BANK_RCP
				SET		ACTUALAMOUNT = CONVERT(DECIMAL (18,2), ISNULL(((SELECT ISNULL(CONVERT (DECIMAL (18,2), SUM(CONVERT(FLOAT,ACC_BANKDTLS_RCP.AMOUNT))),0)  - ISNULL(CONVERT (DECIMAL (18,2), SUM(CONVERT(FLOAT,ACC_BANKDTLS_RCP.DEDUCTION))),0) 
				FROM	ACC_BANKDTLS_RCP WHERE ACC_BANKDTLS_RCP.ENTRYNO = ACC_BANK_RCP.ENTRYNO)),0))
				WHERE	ENTRYNO = @ENTRYNO

			END
			ELSE
			BEGIN
				UPDATE	ACC_BANK
				SET		ACTUALAMOUNT = CONVERT(DECIMAL (18,2), ISNULL(((SELECT ISNULL(CONVERT (DECIMAL (18,2), SUM(CONVERT(FLOAT,ACC_BANKDTLS.AMOUNT))),0)  - ISNULL(CONVERT (DECIMAL (18,2), SUM(CONVERT(FLOAT,ACC_BANKDTLS.DEDUCTION))),0) 
				FROM	ACC_BANKDTLS WHERE ACC_BANKDTLS.ENTRYNO = ACC_BANK.ENTRYNO)),0))
				WHERE	ENTRYNO = @ENTRYNO
			END
			/* END OF UPDATE MASTER TABLE ACTUAL AMOUNT WITH SUM OF [AMOUNT-DEDUCTION] FROM CHILD TABLE */

			--<< FIX: consume temp rows for CC so a duplicate submit cannot copy them again
			IF @STATUS = 'CC'
			BEGIN
				DELETE FROM ACC_BANKDTLS_TMP WHERE VGUID = @VGUID
				DELETE FROM ACC_BANKDTLS_TMP_ORIGNAL WHERE VGUID = @VGUID
			END

			IF @@TRANCOUNT > 0 COMMIT TRANSACTION --<< FIX

			IF (SELECT COUNT(*) FROM	[ACC_BANKDTLS_TMP] 
			WHERE	VGUID = @VGUID AND ISDELETED <> 'Y')>0
			BEGIN

				SELECT	'100' STATUS , [DBO].[FN_ACC_BRBPCRCPCE_FULLNAME](@STATUS) + @ENTRYNO + ' added successfully!' [STATUSTEXT],
					ID,
					ENTRYNO,
					CLIENT,
					JOBNO,
					BILLNO,
					DEDUCTION,
					AMOUNT,
					ENTRYTYPE,
					[dbo].[fn_ENTRYTYPE](ENTRYTYPE) 'ET',
					EMP_CODE,
					USERNAME,
					CRPARENTENTRYNO,
					NARRATION,
					IS_NOT_EDIT_ABLE,
					ITEMCODE,
					DEPTID,
					VGUID,
					ACCOUNT_NAME,
					ITEM,
					DEPARTMENT,
					ACC_BANKDTLS_ID,
					[STATUS] CB_STATUS,
					ISJOBREPORT,ISDELETED,EMP_CODE_VALUE,EMP_CODE_TEXT,ITEM_DATAVALUE
				FROM	[ACC_BANKDTLS_TMP] 
				WHERE	VGUID = @VGUID AND ISDELETED <> 'Y'
			END 
			ELSE
			BEGIN
				SELECT	'100' STATUS , [DBO].[FN_ACC_BRBPCRCPCE_FULLNAME](@STATUS) + @ENTRYNO + ' added successfully!' [STATUSTEXT]
			END

			SELECT	'100#' + [DBO].[FN_ACC_BRBPCRCPCE_FULLNAME](@STATUS) + @ENTRYNO + ' added successfully!' [STATUS], 
					@ENTRYNO ENTRYNO,
					(SELECT CONVERT(DECIMAL (15,2),SUM(ISNULL(CONVERT(FLOAT,AMOUNT),0))) FROM	[ACC_BANKDTLS_TMP] WHERE	VGUID = @VGUID AND ISDELETED <> 'Y') TOTAMOUNT, 
					(SELECT CONVERT(DECIMAL (15,2),SUM(ISNULL(CONVERT(FLOAT,DEDUCTION),0))) FROM	[ACC_BANKDTLS_TMP] WHERE	VGUID = @VGUID AND ISDELETED <> 'Y') TOTDEDUCTION, 
					(SELECT CONVERT(DECIMAL (15,2),SUM(ISNULL(CONVERT(FLOAT,AMOUNT),0))) - CONVERT(DECIMAL (15,2),SUM(ISNULL(CONVERT(FLOAT,DEDUCTION),0))) FROM	[ACC_BANKDTLS_TMP] WHERE VGUID = @VGUID AND ISDELETED <> 'Y') NETTOTAL
		END
		ELSE
		BEGIN
			--SELECT '103#Adding failed ' + @ENTRYNO + ' already exists! Please sumbit again.' [STATUS]
			SELECT '103#Adding failed! Please sumbit again.' [STATUS]
		END
	END -- END OF CHEQUE NO VALIDATION.....
--END -- END OF BEGIN....

ERROR_HANDLER:
BEGIN
	IF @@TRANCOUNT != 0 ROLLBACK TRANSACTION
	SELECT	'103#SQL ERROR! ERROR NO. ' 
			--+ CONVERT(VARCHAR,ERROR_NUMBER()) 
			--+ ' LINE NO. ' + CONVERT(VARCHAR,ERROR_LINE()) 
			--+ ' msg : ' + ERROR_MESSAGE()
			[STATUS]
END
GO
