USE [LinksDB]
GO
/**********************************************************************************************
 FIX : USP_Acc_INV_Print_New  -  additional columns for the new standard TAX INVOICE print
 DATE: 18-07-2026

 PURELY ADDITIVE - no existing column, resultset order or logic is changed, so the current
 invoice print page and the Crystal bulk-print keep working unchanged until the new page is
 deployed. Added columns:
   1) Invoice master resultset : EXP_GSTNO, EXP_GSTSTATE, PARTY_STATECODE,
      POS_STATENAME, POS_STATECODE, CITY_COUNTRY_RAW
      (party GSTIN / state / place of supply as clean fields instead of HTML embedded
       inside CITY_COUNTRY; CITY_COUNTRY itself is untouched)
   2) Charges resultset        : SACCODE, CHRG_DESC_PLAIN
      (SAC as its own column; CHRG_DESC keeps the "[ SAC ] description" decoration)
   3) QR-code resultset        : ACKNO, ACKDATE  (e-invoice acknowledgement)

 DEPLOY : run on the LIVE LinksDB server (123.108.50.248,21443). Verify the catalog name
          before running; adjust the USE statement if the live catalog differs.
 ROLLBACK: ROLLBACK_USP_Acc_INV_Print_New_20260718.sql (definition captured 18-07-2026).
**********************************************************************************************/


--EXEC USP_Acc_INV_Print_New '301102006100012' ,'30','MUM'
 
ALTER PROCEDURE [dbo].[USP_Acc_INV_Print_New]    
--DECLARE
@inv_no varchar(15),    
@cmp_code varchar(2),    
@city_code varchar(3)    

AS/*
set @inv_no='301102203100055'   --011011707100006
set @cmp_code='30'  
set @city_code='mum'
--*/  

SET NOCOUNT ON  
  
   /* Changes for All city, Where user can take the print of invoice by inputing Invoice no */  

	SELECT	@CITY_CODE=CMP_ADDRESS.CMP_CITY
	FROM   CMP_ADDRESS
	WHERE CMP_ADDRESS.CMP_CODE=SUBSTRING(@INV_NO,1,2) AND  CMP_ADDRESS.CMP_CTYCODE = SUBSTRING(@INV_NO,3,3)
   /* -------------------------------------------------------------------------------------- */  

	DECLARE @INV_DATE1 NVARCHAR(10),
			@STAXNOTIFY varchar(500),
			@STAEDTLS varchar(500),
			@INVCLIENT VARCHAR(10)
			
	SET @STAXNOTIFY=''
	SET @STAEDTLS=''
	SET @INVCLIENT=''

	SELECT @INVCLIENT=INV_CLIENT 
	FROM   ACC_INVOICE
	WHERE  INV_NO = @INV_NO 
		   AND CMPCODE = @CMP_CODE 
		   AND CITYCODE = @CITY_CODE  

	SELECT  @INV_DATE1 =  DBO.CONVERTDATE_YYYYMMDD(INV_DATE) 
	FROM	ACC_INVOICE 
	WHERE	INV_NO = @INV_NO


	IF @INV_DATE1 < '20120701'
	BEGIN
		SET @STAXNOTIFY='Service Tax on Transporation is payable by the Consignee in terms of Notification No. 35/200 Dt. 3/12/2004. Please ensure you pay the service tax on transporation.'
	end
	ELSE IF @INV_DATE1 BETWEEN '20120701' AND '20170630'
	begin
		SET @STAXNOTIFY='Service Tax on Transporation is payable by the Consignee in terms of Notification No. 30/2012 Dt. 20/06/2012. Please ensure you pay the service tax on transporation.'
	end
	ELSE IF @INV_DATE1 >= '20170701' 
	begin
		--SET @STAXNOTIFY='As per CGST Act , Section 9(3) read with Reverse charge notificaton (Sr. 2) , Tax Liability on GTA services shall be paid by Service Receiver.'
		SET @STAXNOTIFY=''
	end

	SELECT	CMP_ADDRESS.CMP_CODE, CMP_ADDRESS.CMP_NAME, CMP_ADDRESS.CMP_FULLNAME, CMP_ADDRESS.CMP_BOLDNAME,     
			CMP_ADDRESS.CMP_IMAGE, CMP_ADDRESS.CMP_EMAIL, CMP_ADDRESS.CMP_ADD1, CMP_ADDRESS.CMP_ADD2,     
			CMP_ADDRESS.CMP_ADD3, CMP_ADDRESS.CMP_CITY, CMP_ADDRESS.CMP_CTYCODE, CITY_MASTER.CITY_CODE, CITY_MASTER.CITY_NAME,     
			CITY_MASTER.CITY_COUNTRY, CMP_ADDRESS.CMP_TELNO, CMP_ADDRESS.CMP_FAXNO, CMP_ADDRESS.CMP_CUSTLICNO,     
			CMP_ADDRESS.CMP_IATACODE, 
			SERVICETAX_REGD=CASE WHEN @INV_DATE1 <= '20170630' THEN 
									'Service Tax Reg. - ' + ISNULL(CMP_ADDRESS.SERVICETAX_REGD, '') 
								ELSE 
									'GSTIN  - ' + ISNULL(GSTIN,'') 
								END ,  
			ISNULL(CMP_ADDRESS.TPTSRVTAX_REGD, '') AS TPTSRVTAX_REGD,    
			ISNULL(CMP_ADDRESS.AUXSRVTAX_REGD, '')  AS AUXSRVTAX_REGD,  
			ISNULL(CMP_ADDRESS.STORAGESRVTAX_REGD, '') AS STORAGESRVTAX_REGD,     
			ISNULL(CMP_ADDRESS.CHSRVTAX_REGD, '') AS CHSRVTAX_REGD, 
			ISNULL(ESIC_REGD, '') AS ESIC_REGD,
			ISNULL(INCOMETAXNO, '') AS INCOMETAXNO   ,
			ISNULL(CINNO_REG,'')CINNO_REG,
			GSTIN=ISNULL(GSTIN,''),
			'Regd. Office : ' + CMP_ADD1 + CMP_ADD2 + CMP_ADD3 + ', GSTIN - ' + GSTIN AS CMPADDRESS,
			STATECODE='State Code No. ' +CITY_MASTER.STATE_TIN,
			STATENAME='State: '+CITY_MASTER.STATE_NAME,
			PANNO='PAN No. ' + 'ATXGJK45223'
	FROM    CMP_ADDRESS LEFT OUTER JOIN    
			CITY_MASTER ON CMP_ADDRESS.CMP_CITY = CITY_MASTER.CITY_CODE    
	WHERE  CMP_ADDRESS.CMP_CODE = @CMP_CODE AND  CMP_ADDRESS.CMP_CITY = @CITY_CODE    
    
    --SELECT * FROM EXP_MSTINVADD 
    /* Getting the place of supply */
    DECLARE @BLTOSTATE NVARCHAR(5),	@BLFRMSTATE NVARCHAR(5), @JOB_COUNTRY NVARCHAR(3), 
			@JOBCITY1 NVARCHAR(3),  @ISOVERSEAS NVARCHAR(1), @PLACEOFSUPPLY NVARCHAR(20), @CLIENT_COUNTRY NVARCHAR(3)

	SELECT	@ISOVERSEAS = CASE WHEN ISNULL(LTRIM(RTRIM(EXP_INVCOUNTRY)),'') IN ('IN','IND')  THEN '0' ELSE '1' END,
			@CLIENT_COUNTRY = ISNULL(LTRIM(RTRIM(EXP_INVCOUNTRY)),'')
	FROM	ACC_INVOICE INV INNER JOIN 
			EXP_MSTINVADD EXPADD ON INV.INV_ADDID=EXPADD.PK_INVADD_ID
	WHERE	INV_NO = @INV_NO 
	
	IF @ISOVERSEAS='1'
	BEGIN
		SET @JOBCITY1 = (SELECT TOP 1 SUBSTRING(INV_JOBNO, 3,3) FROM ACC_INVJOBNO WHERE INV_NO =@inv_no)

		SELECT	@JOB_COUNTRY=LTRIM(RTRIM(ISNULL(ISO_COUNTRY_CODE,''))) 
		FROM	CITY_MASTER 
		WHERE	CITY_CODE IN(SELECT cmp_city FROM CMP_ADDRESS WHERE cmp_ctycode IN (@JOBCITY1))

		IF @JOB_COUNTRY = 'IN' OR @JOB_COUNTRY = 'IND'
		BEGIN
			SELECT	@PLACEOFSUPPLY=LTRIM(RTRIM(ISNULL(STATE_CODE,'')))
			FROM	CITY_MASTER 
			WHERE	CITY_CODE IN(SELECT CMP_CITY FROM CMP_ADDRESS WHERE CMP_CTYCODE IN (@JOBCITY1))
		END
		ELSE
		BEGIN
			SELECT	@PLACEOFSUPPLY=LTRIM(RTRIM(ISNULL(STATE_CODE,''))) 
			FROM	CITY_MASTER 
			WHERE	CITY_CODE IN(SELECT CITYCODE FROM CITY WHERE CITYCODE1 IN (@JOBCITY1))
		END
	END
	ELSE
	BEGIN
		SELECT	@PLACEOFSUPPLY=(SELECT EXP_INVSTATE FROM EXP_MSTINVADD WHERE PK_INVADD_ID=ACC_INVOICE.INV_ADDID)
		FROM	ACC_INVOICE 
		WHERE	INV_NO = @INV_NO 
	END
    
    /* End of place of supply */
    
	SELECT  ACCINV.INV_NO, ACCINV.INV_DATE, 
			ACCINV.INV_CLIENT, ACCINV.INV_SHIPPER, ACCINV.INV_BILLTYPE,     
			ACCINV.INV_PKGS, ACCINV.INV_TYPEOFPKG, ACCINV.INV_NOOFPCS, ACCINV.INV_TYPEOFPCS, ACCINV.INV_CLIENTREF,    
			ACCINV.INV_WT, ACCINV.INV_VOL, ACCINV.INV_HAWBNO, ACCINV.INV_HAWBDT, ACCINV.INV_CARRIER,     
			ACCINV.INV_GOODS,ACCINV.INV_CUR, ACCINV.INV_CURINR, ACCINV.INV_CURRATE, ACCINV.INV_CURRATE1,     
			ACCINV.INV_TAX, 
			ISNULL(CONVERT(FLOAT, ACCINV.INV_ADVANCE), 0) AS INV_ADVANCE, 
			EXPM.EXP_NAME, 
			EXPM.EXP_CITY, 
			EXP_INVCITY= CASE WHEN ISNULL(INVADD.EXP_INVCITY,'') ='' THEN  LTRIM(RTRIM(ISNULL(EXPM.EXP_INVCITY,''))) ELSE  LTRIM(RTRIM(ISNULL(INVADD.EXP_INVCITY,''))) END, 
			CITY_NAME= CASE WHEN ISNULL(INVADD.exp_invpinposition,'') ='' THEN
							CASE EXPM1.EXP_INVPINPOSITION 
								WHEN 'AFTER' THEN LTRIM(RTRIM(CITYM1.CITY_NAME)) + ' ' +  LTRIM(RTRIM(CONVERT(NVARCHAR(10),EXPM.EXP_INVPINCODE)))   
								WHEN 'BEFORE' THEN LTRIM(RTRIM(CONVERT(NVARCHAR(10),EXPM.EXP_INVPINCODE))) + ' ' + LTRIM(RTRIM(CITYM1.CITY_NAME))   
									ELSE CITYM1.CITY_NAME END 
						ELSE
							CASE INVADD.EXP_INVPINPOSITION 
								WHEN 'AFTER' THEN LTRIM(RTRIM(CITYM.CITY_NAME)) + ' ' +  LTRIM(RTRIM(CONVERT(NVARCHAR(10),INVADD.EXP_INVPINCODE)))   
								WHEN 'BEFORE' THEN LTRIM(RTRIM(CONVERT(NVARCHAR(10),INVADD.EXP_INVPINCODE))) + ' ' + LTRIM(RTRIM(CITYM.CITY_NAME))   
									ELSE CITYM.CITY_NAME END 			
					  END,
			CITY_COUNTRY = CASE WHEN @INV_DATE1 >= '20170701' THEN  
								LTRIM(RTRIM(ISNULL(CITYM.CITY_COUNTRY,''))) 
								+ ' <BR> GSTIN : '+ (CASE WHEN ISNULL(INVADD.EXP_GSTNO,'') ='' THEN '' ELSE ISNULL(INVADD.EXP_GSTNO,'') END)+  
								+ '       STATE : '+ (CASE WHEN ISNULL(INVADD.EXP_INVSTATE,'') ='' THEN '' ELSE ISNULL(INVADD.EXP_INVSTATE,'') END) + ' - '+ SUBSTRING(ISNULL(INVADD.EXP_GSTNO,''),1,2)  +  
								+ ' <BR> PLACE OF SUPPLY : '+(SELECT TOP 1 LTRIM(RTRIM(ISNULL(STATE_NAME,''))) FROM CITY_MASTER WHERE LTRIM(RTRIM(ISNULL(STATE_CODE,'')))= @PLACEOFSUPPLY) --ISNULL(INVADD.EXP_INVSTATE,'')) 
							ELSE 
								LTRIM(RTRIM(ISNULL(CITYM.CITY_COUNTRY,'')))
							END	,
			EXP_INVADD1= CASE WHEN ISNULL(INVADD.EXP_INVADD1,'') ='' THEN  LTRIM(RTRIM(ISNULL(EXPM.EXP_INVADD1,''))) ELSE  LTRIM(RTRIM(ISNULL(INVADD.EXP_INVADD1,''))) END, 
			EXP_INVADD2= CASE ISNULL(INVADD.EXP_INVADD1,'') 
								WHEN '' THEN  LTRIM(RTRIM(ISNULL(EXPM.EXP_INVADD2,''))) 
								ELSE  LTRIM(RTRIM(ISNULL(INVADD.EXP_INVADD2,''))) END, 
			EXP_INVADD3= CASE ISNULL(INVADD.EXP_INVADD1,'') 
								WHEN '' THEN  LTRIM(RTRIM(ISNULL(EXPM.EXP_INVADD3,''))) 
								ELSE  LTRIM(RTRIM(ISNULL(INVADD.EXP_INVADD3,''))) END, 
			EXP_INVPINCODE= CASE WHEN ISNULL(INVADD.EXP_INVPINCODE,'') ='' THEN  LTRIM(RTRIM(ISNULL(EXPM.EXP_INVPINCODE,''))) ELSE  LTRIM(RTRIM(ISNULL(INVADD.EXP_INVPINCODE,''))) END, 
			EXPM1.EXP_NAME AS DOCTHROUGH, 
			CURM.CUR_NAME, 
			NARRATION=LTRIM(RTRIM(ACCINV.NARRATION)),
			PAYBLEBYDT = CASE WHEN  ACCINV.PAYBYDT IS NULL THEN '' ELSE REPLACE(CONVERT(VARCHAR,ACCINV.PAYBYDT,106),' ','-') END
			,STAXNOTIFY=@STAXNOTIFY,
			PLACEOFSUPPLY ='Place of Supply: ' + (SELECT TOP 1 LTRIM(RTRIM(ISNULL(STATE_NAME,''))) FROM CITY_MASTER WHERE LTRIM(RTRIM(ISNULL(STATE_CODE,'')))= @PLACEOFSUPPLY),
			/* === ADDED 18-07-2026 : clean GST fields for the new TAX INVOICE print (additive - old pages unaffected) === */
			EXP_GSTNO = ISNULL(INVADD.EXP_GSTNO,''),
			EXP_GSTSTATE = ISNULL(INVADD.EXP_INVSTATE,''),
			PARTY_STATECODE = SUBSTRING(ISNULL(INVADD.EXP_GSTNO,''),1,2),
			POS_STATENAME = ISNULL((SELECT TOP 1 LTRIM(RTRIM(ISNULL(STATE_NAME,''))) FROM CITY_MASTER WHERE LTRIM(RTRIM(ISNULL(STATE_CODE,'')))= @PLACEOFSUPPLY),''),
			POS_STATECODE = ISNULL(@PLACEOFSUPPLY,''),
			CITY_COUNTRY_RAW = LTRIM(RTRIM(ISNULL(CITYM.CITY_COUNTRY,'')))
			/* === END ADDED === */
	FROM	ACC_INVOICE ACCINV 
			LEFT OUTER JOIN CUR_MASTER CURM ON ACCINV.INV_CUR =CURM.CUR_CODE
			LEFT OUTER JOIN EXP_MASTER EXPM ON ACCINV.INV_CLIENT =EXPM.EXP_CODE
			LEFT OUTER JOIN EXP_MASTER EXPM1 ON ACCINV.INV_SHIPPER =EXPM1.EXP_CODE
			LEFT OUTER JOIN EXP_MSTINVADD INVADD ON INVADD.PK_INVADD_ID=ACCINV.INV_ADDID
			LEFT OUTER JOIN CITY_MASTER CITYM ON CITYM.CITY_CODE =INVADD.EXP_INVCITY
			LEFT OUTER JOIN CITY_MASTER CITYM1 ON CITYM1.CITY_CODE =EXPM.EXP_INVCITY
			
	WHERE   ACCINV.INV_NO = @INV_NO 
			AND CMPCODE = @CMP_CODE 
			AND CITYCODE = @CITY_CODE    
		
	--FROM  CUR_MASTER 
	--		RIGHT OUTER JOIN ACC_INVOICE ACCINV ON CUR_MASTER.CUR_CODE = ACCINV.INV_CUR 
	--		LEFT OUTER JOIN EXP_MASTER EXPM1 ON ACCINV.INV_SHIPPER = EXPM1.EXP_CODE 
	--		LEFT OUTER JOIN CITY_MASTER RIGHT OUTER JOIN    
	--		EXP_MASTER EXPM ON CITY_MASTER.CITY_CODE = EXPM.EXP_INVCITY ON ACCINV.INV_CLIENT = EXPM.EXP_CODE    
	--		LEFT OUTER JOIN EXP_MSTINVADD INVADD ON INVADD.PK_INVADD_ID=ACCINV.INV_ADDID
   
	SELECT INV_JOBNO FROM ACC_INVJOBNO WHERE INV_NO = @INV_NO ORDER BY ID    

	SELECT * FROM ACC_INVENCLOSURE1 WHERE INV_NO= @INV_NO ORDER BY INV_ENCLCODE    
	--chargs     
	-- SELECT * FROM EXP_MASTER WHERE EXP_CODE='E105167'

	SELECT  ACC_INVCHARGE.INV_CHRGCODE, 
			ACC_INVCHARGE.INV_ACCOUNT, 
			GENACCT_MASTER.ACCTNAME, 
			LTRIM(RTRIM(ACC_CHARGEMASTER.CHRG_DESC + ISNULL(ACC_CHARGEMASTER.CHRG_DESC1, ''))) AS CHRG_DESC,     
			-- ACC_CHARGEMASTER.CHRG_DESC1 AS INV_DESC,     
			ACC_INVCHARGE.INV_DESC,     
			ACC_INVCHARGE.INV_TAXABLE, 
			ACC_INVCHARGE.INV_AMOUNT, 
			ACC_INVCHARGE.INV_INRAMT, 
			ACC_INVCHARGE.ID,     
			ACC_INVCHARGE.INV_NO,
			SACCODE=ISNULL(GENACCT_MASTER.SACCODE,''),
			'1' AS TBLCHRGS,
			LTRIM(RTRIM(ISNULL(ACC_INVCHARGE.INV_QTY,0.000)))INV_QTY,
			LTRIM(RTRIM(ISNULL(ACC_INVCHARGE.INV_RATE,0.00)))INV_RATE,
			LTRIM(RTRIM(ISNULL(CUR_MASTER.CUR_NAME,''))) INV_CURRENCY,
			LTRIM(RTRIM(ISNULL(ACC_INVCHARGE.INV_EXRATE,0.00)))  INV_EXRATE
	INTO	#1    
	FROM    ACC_INVCHARGE LEFT OUTER JOIN    
			GENACCT_MASTER ON ACC_INVCHARGE.INV_ACCOUNT = GENACCT_MASTER.ACCTCODE LEFT OUTER JOIN    
			ACC_CHARGEMASTER ON ACC_INVCHARGE.INV_CHRGCODE = ACC_CHARGEMASTER.CHRG_CODE    LEFT OUTER JOIN 
			CUR_MASTER ON CUR_MASTER.CUR_CODE=ACC_INVCHARGE.inv_currency 
	WHERE  (ACC_INVCHARGE.INV_TAXABLE IS NOT NULL) AND ACC_INVCHARGE.INV_NO = @INV_NO    
     
	INSERT INTO #1 (INV_CHRGCODE, INV_ACCOUNT, ACCTNAME, CHRG_DESC, INV_DESC, INV_TAXABLE, INV_AMOUNT, INV_INRAMT, ID, INV_NO,SACCODE,TBLCHRGS,INV_QTY,INV_RATE,INV_CURRENCY,INV_EXRATE)    
	SELECT	ACC_INVCHARGE1.INV_CHRGCODE, ACC_INVCHARGE1.INV_ACCOUNT, 
			GENAMST.ACCTNAME, 
			ACC_INVCHARGE1.INV_DESC1,-- +  ACC_INVCHARGE1.INV_DESC2,     
			ACC_INVCHARGE1.INV_DESC2, 
			ACC_INVCHARGE1.INV_TAXABLE, 
			ACC_INVCHARGE1.INV_AMOUNT,  
			ACC_INVCHARGE1.INV_INRAMT, 
			ACC_INVCHARGE1.ID,     
			ACC_INVCHARGE1.INV_NO,
			SACCODE=ISNULL(GENAMST.SACCODE,''),
			'2'  ,
				LTRIM(RTRIM(ISNULL(ACC_INVCHARGE1.INV_QTY,0.000)))INV_QTY,
			LTRIM(RTRIM(ISNULL(ACC_INVCHARGE1.INV_RATE,0.00)))INV_RATE,
			LTRIM(RTRIM(ISNULL(CUR_MASTER.CUR_NAME,''))) INV_CURRENCY,
			LTRIM(RTRIM(ISNULL(ACC_INVCHARGE1.INV_EXRATE,0.00)))  INV_EXRATE
	FROM	ACC_INVCHARGE1 LEFT OUTER JOIN    
			GENACCT_MASTER GENAMST ON ACC_INVCHARGE1.INV_ACCOUNT = GENAMST.ACCTCODE LEFT OUTER JOIN    
			ACC_CHARGEMASTER ON ACC_INVCHARGE1.INV_CHRGCODE = ACC_CHARGEMASTER.CHRG_CODE    LEFT OUTER JOIN 
			CUR_MASTER ON CUR_MASTER.CUR_CODE=ACC_INVCHARGE1.inv_currency
	WHERE	ACC_INVCHARGE1.INV_NO =  @INV_NO    
     
	--SELECT * FROM #1 ORDER BY TBLCHRGS,INV_CHRGCODE,ID    
	SELECT	INV_CHRGCODE, 
			CASE WHEN ISNULL(SACCODE,'') <>'' THEN 
					'[ ' + ISNULL(SACCODE,'') + ' ] ' +  ISNULL(CHRG_DESC, '') + ' ' + ISNULL( INV_DESC, '') 
				ELSE 
					ISNULL(CHRG_DESC, '') + ' ' + ISNULL( INV_DESC, '') 
				END AS CHRG_DESC, 
			INV_TAXABLE,    
			INV_AMOUNT_Y = CASE WHEN INV_TAXABLE <> 'N' THEN ISNULL(CONVERT(FLOAT, ISNULL(INV_AMOUNT, 0)), 0 )ELSE 0 END,    
			INV_AMOUNT_N = CASE WHEN INV_TAXABLE = 'N' THEN CONVERT(FLOAT, ISNULL(INV_AMOUNT, 0)) ELSE 0 END,    
			INV_INRAMT_Y = CASE WHEN INV_TAXABLE <> 'N' THEN CONVERT(FLOAT, ISNULL(INV_INRAMT, 0)) ELSE 0 END,    
			INV_INRAMT_N = CASE WHEN INV_TAXABLE = 'N' THEN CONVERT(FLOAT, ISNULL(INV_INRAMT, 0)) ELSE 0 END,
			INV_QTY, INV_RATE, INV_CURRENCY,INV_EXRATE,
			/* === ADDED 18-07-2026 : SAC as separate column + plain description (old CHRG_DESC keeps the [SAC] prefix for the old page) === */
			SACCODE = ISNULL(SACCODE,''),
			CHRG_DESC_PLAIN = LTRIM(RTRIM(ISNULL(CHRG_DESC,'') + ' ' + ISNULL(INV_DESC,'')))
			--INV_AMOUNT, INV_INRAMT     
	FROM	#1  
	ORDER BY TBLCHRGS,INV_CHRGCODE,ID    
     
	--Narration    
	--select * from acc_invenclosure Where inv_no = @inv_no  -- Narration    
	--select '1' as Narr    
	SELECT	TOT_INV_AMOUNT_Y = (SELECT ISNULL(SUM(CONVERT(FLOAT,INV_AMOUNT)), 0) FROM #1 WHERE INV_TAXABLE <> 'N'),    
			TOT_INV_AMOUNT_N = (SELECT ISNULL(SUM(CONVERT(FLOAT,INV_AMOUNT)), 0) FROM #1 WHERE INV_TAXABLE = 'N'),    
			TOT_INV_INRAMT_Y = (SELECT ISNULL(SUM(CONVERT(FLOAT,INV_INRAMT)), 0) FROM #1 WHERE INV_TAXABLE <> 'N'),    
			TOT_INV_INRAMT_N = (SELECT ISNULL(SUM(CONVERT(FLOAT,INV_INRAMT)), 0) FROM #1 WHERE INV_TAXABLE = 'N')   

	DROP TABLE #1    

	SELECT * FROM ACC_INVDESPATCH WHERE INV_NO = @INV_NO ----   DESPATCH    
 
 /*
	START REPRESENTATION OF SERVICE TAX OR GST 
    ON 04/07/2017 BY SUJIT SAHOO 
    AS PER THE SERVICE TAX /GST NOTIFICATION
  
 */   
 
	DECLARE @INVDATE  DATETIME    
	SELECT @INVDATE= DBO.CONVERTDATE_IN_US(INV_DATE, '/') FROM ACC_INVOICE WHERE INV_NO = @INV_NO    
	
	--PRINT @INVDATE    
	IF OBJECT_ID('TEMPDB..#TINVCHARGE') IS NOT NULL    
	DROP TABLE #TINVCHARGE     
	
	CREATE TABLE #TINVCHARGE    
	(    
		INV_AMOUNT DECIMAL(15,2),    
		INV_INRAMT DECIMAL(15,2),    
		TAXABLEAMT DECIMAL(15,2),    
		TAXABLEAMTINR DECIMAL(15,2),    
		INV_TAXABLE VARCHAR(1),
		INV_CHRGCODE varchar(5),
		INV_ACCOUNT varchar(7)    
	)    

	INSERT INTO #TINVCHARGE    
	SELECT	CASE WHEN INV_AMOUNT = '' THEN 0 ELSE CONVERT(DECIMAL(15,2),  INV_AMOUNT) END AS INV_AMOUNT,    
			CASE WHEN INV_INRAMT = '' THEN 0 ELSE CONVERT(DECIMAL(15,2), INV_INRAMT) END AS INV_INRAMT,     
			TAXABLEAMT,    
			TAXABLEAMTINR,    
			INV_TAXABLE = CASE WHEN INV_TAXABLE='G' THEN 
							CASE WHEN INV_ACCOUNT IN ('G101610') THEN 'O' ELSE  INV_TAXABLE END
						ELSE  INV_TAXABLE END,
			INV_CHRGCODE,
			INV_ACCOUNT        
	FROM    ACC_INVCHARGE    
	WHERE  INV_NO = @INV_NO AND RTRIM(INV_TAXABLE) <> 'N'    

	INSERT INTO #TINVCHARGE    
	SELECT	CASE WHEN INV_AMOUNT = '' THEN 0 ELSE  CONVERT(DECIMAL(15,2),  INV_AMOUNT) END AS INV_AMOUNT,    
			CASE WHEN INV_INRAMT = '' THEN 0 ELSE  CONVERT(DECIMAL(15,2), INV_INRAMT) END AS INV_INRAMT,     
			TAXABLEAMT,    
			TAXABLEAMTINR,    
			INV_TAXABLE = CASE WHEN INV_TAXABLE='G' THEN 
								CASE WHEN INV_ACCOUNT IN ('G101610') THEN 'O' ELSE  INV_TAXABLE END
							ELSE  INV_TAXABLE END,
			INV_CHRGCODE,
			INV_ACCOUNT
	FROM   ACC_INVCHARGE1    
	WHERE  INV_NO = @INV_NO AND RTRIM(INV_TAXABLE) <> 'N'   
	
	IF(SELECT COUNT(*) FROM #TINVCHARGE)=1
	BEGIN
		UPDATE #TINVCHARGE SET INV_TAXABLE='G' 
		WHERE INV_TAXABLE='O' AND INV_ACCOUNT='G101610'
	END 

	/*
		GATEHERING ALL THE TAX CODES 
		FROM THE TABLE [TBL_ACC_INV_STAX] BY FILTERING 
		FROM TABLE [ACC_INVCHARGE]
	*/
	
	IF OBJECT_ID('TEMPDB..#TMP_TBL_ACC_INV_STAX') IS NOT NULL    
	DROP TABLE #TMP_TBL_ACC_INV_STAX
	   
	CREATE TABLE #TMP_TBL_ACC_INV_STAX
	(	ID	int,
		STCode nvarchar(100),
		Name nvarchar(2000),
		SName nvarchar(1000),
		chrgcode nvarchar(5),
		Acctcode nvarchar(7)
		--chrg_desc NVARCHAR(100),
	)

	INSERT INTO #TMP_TBL_ACC_INV_STAX
	SELECT	ID, STCODE,	NAME, SNAME, CHRGCODE, Acctcode
	FROM	TBL_ACC_INV_STAX  
	WHERE	STCODE IN (SELECT DISTINCT INV_TAXABLE FROM #TINVCHARGE)
			AND ISNULL(CHRGCODE,'') <>''
			
	INSERT INTO #TMP_TBL_ACC_INV_STAX	
	SELECT	ID, STCODE,	NAME, SNAME, CGSTCHRGCODE, CGSTAcctcode
	FROM	TBL_ACC_INV_STAX 
	WHERE	STCODE IN ( SELECT INV_TAXABLE FROM #TINVCHARGE WHERE INV_TAXABLE='G')

	INSERT INTO #TMP_TBL_ACC_INV_STAX
	SELECT	ID, STCODE,	NAME, SNAME, SGSTCHRGCODE, SGSTAcctcode
	FROM	TBL_ACC_INV_STAX  
	WHERE	STCODE IN ( SELECT INV_TAXABLE FROM #TINVCHARGE WHERE INV_TAXABLE='G')

	INSERT INTO #TMP_TBL_ACC_INV_STAX
	SELECT	ID, STCODE,	NAME, SNAME, IGSTCHRGCODE, IGSTAcctcode
	FROM	TBL_ACC_INV_STAX  
	WHERE	STCODE IN ( SELECT INV_TAXABLE FROM #TINVCHARGE WHERE INV_TAXABLE='G')

	INSERT INTO #TMP_TBL_ACC_INV_STAX
	SELECT	ID, STCODE='O',	NAME, SNAME, STMFCGSTCHRGCODE, StmfCGSTAcctcode
	FROM	TBL_ACC_INV_STAX  
	WHERE	STCODE IN ( SELECT INV_TAXABLE FROM #TINVCHARGE WHERE INV_TAXABLE='G')

	INSERT INTO #TMP_TBL_ACC_INV_STAX
	SELECT	ID, STCODE='O',	NAME, SNAME, STMFSGSTCHRGCODE, StmfSGSTAcctcode
	FROM	TBL_ACC_INV_STAX  
	WHERE	STCODE IN ( SELECT INV_TAXABLE FROM #TINVCHARGE WHERE INV_TAXABLE='G')

	INSERT INTO #TMP_TBL_ACC_INV_STAX
	SELECT	ID, STCODE='O',	NAME, SNAME, STMFIGSTCHRGCODE, StmfIGSTAcctcode	
	FROM	TBL_ACC_INV_STAX 
	WHERE	STCODE IN ( SELECT INV_TAXABLE FROM #TINVCHARGE WHERE INV_TAXABLE='G')

	/*
		DELETE THE CHARGECODE FROM THE TABLE [TBL_ACC_INV_STAX] 
		WHICH ARE NOT REQUIRE FOR THIS INV TO PRINT
	*/
	DELETE #TMP_TBL_ACC_INV_STAX 
	WHERE CHRGCODE NOT IN (SELECT inv_chrgcode FROM ACC_INVCHARGE  WHERE INV_NO=@INV_NO) 

	IF(SELECT COUNT(*) FROM #TINVCHARGE)=1
	BEGIN
		UPDATE #TINVCHARGE SET INV_TAXABLE='O' 
		WHERE INV_TAXABLE='G' AND INV_ACCOUNT='G101610'
	END
	
	/*
		GET THE CHRGCODE WISE TAXABLE INV_AMOUNT 
	*/

	IF OBJECT_ID('TEMPDB..#TINVCHARGE1') IS NOT NULL    
	DROP TABLE #TINVCHARGE1 
	CREATE TABLE #TINVCHARGE1   
	(    
		INV_AMOUNT DECIMAL(15,2),    
		INV_INRAMT DECIMAL(15,2),    
		TAXABLEAMT DECIMAL(15,2),    
		TAXABLEAMTINR DECIMAL(15,2),    
		INV_TAXABLE VARCHAR(1),
		CHRGCODE varchar(5)--,
		--ACCOUNT varchar(7)
	) 

	INSERT INTO #TINVCHARGE1
	SELECT	SUM(CONVERT(DECIMAL(15,2), CHRG.INV_AMOUNT)) AS INV_AMOUNT,    
			SUM(CONVERT(DECIMAL(15,2), CHRG.INV_INRAMT)) AS INV_INRAMT,    
			SUM(CONVERT(DECIMAL(15,2), CHRG.TAXABLEAMT)) AS TAXABLEAMT,    
			SUM(CONVERT(DECIMAL(15,2), CHRG.TAXABLEAMTINR)) AS TAXABLEAMTINR,    
			INV_TAXABLE=(CASE WHEN CHRG.INV_TAXABLE='O' THEN 'G' ELSE CHRG.INV_TAXABLE END) ,    
			STAX.CHRGCODE 
			--,CHRG.INV_ACCOUNT  
	FROM	#TINVCHARGE CHRG LEFT OUTER JOIN     
			#TMP_TBL_ACC_INV_STAX STAX ON STAX.STCODE = CHRG.INV_TAXABLE    
	GROUP BY INV_TAXABLE, STAX.CHRGCODE    

	/*
	  SERVICE TAX CODE MAPPING  CHARGECODE  
		--9920	- 9951 --A -->9921	- 9952 --X -->9922	- 9955 --T -->9923	- 9954 --S -->9924	- 9953 --C
	*/
		
	IF OBJECT_ID('TEMPDB..#PRINT_INVCHARGE1') IS NOT NULL    
	DROP TABLE #PRINT_INVCHARGE1        

	CREATE TABLE #PRINT_INVCHARGE1    
	(    
		PK_ID INT IDENTITY(1,1) NOT NULL,
		inv_chrgcode NVARCHAR(10),	
		inv_desc VARCHAR(200),
		inv_amount DECIMAL(15,2),	
		inv_inramt DECIMAL(15,2),	
		TaxableAmt DECIMAL(15,2),	
		TaxableAmtINR DECIMAL(15,2),
		SName VARCHAR(50),	
		Totinv_amount DECIMAL(15,2),	
		Totinv_inramt DECIMAL(15,2),	
		Rate DECIMAL(15,2),	
		Desc1 VARCHAR(150),
		--STAX_CHRGCODE NVARCHAR(10),
		SBC_CHRGCODE NVARCHAR(10),
		KKC_CHRGCODE NVARCHAR(10))
    
IF EXISTS(SELECT INV_CHRGCODE FROM ACC_INVCHARGE WHERE INV_NO = @INV_NO AND INV_TAXABLE<>'N' 
		  UNION 
		  SELECT INV_CHRGCODE FROM ACC_INVCHARGE1 WHERE INV_NO = @INV_NO AND INV_TAXABLE <>'N')    
BEGIN    
	INSERT INTO #PRINT_INVCHARGE1	
	SELECT	INVCHRG.INV_CHRGCODE,     
			INVCHRG.INV_DESC ,     
			CONVERT(DECIMAL(15,2), INVCHRG.INV_AMOUNT) AS INV_AMOUNT,     
			CONVERT(DECIMAL(15,2), INVCHRG.INV_INRAMT) AS INV_INRAMT,     
			CONVERT(DECIMAL(15,2), INVCHRG.TAXABLEAMT) AS TAXABLEAMT,     
			CONVERT(DECIMAL(15,2), INVCHRG.TAXABLEAMTINR) AS TAXABLEAMTINR,    
			ISNULL(SNAME, (ISNULL(CHRGMST.CHRG_DESC,'') + ' ' + ISNULL(CHRGMST.CHRG_DESC1,''))) AS SNAME,     
			--ISNULL(#TINVCHARGE1.TAXABLEAMT, 0) AS TOTINV_AMOUNT, 
			TOTINV_AMOUNT= ISNULL(CHRG1.INV_AMOUNT, 0) ,	
			ISNULL(CHRG1.TAXABLEAMTINR, 0) AS TOTINV_INRAMT,    
			ISNULL((SELECT  CASE INV_CHRGCODE WHEN '9961' THEN CGSTRATE
								WHEN '9962' THEN SGSTRATE
								WHEN '9963' THEN IGSTRATE
								WHEN '9964' THEN STMFCGSTRATE
								WHEN '9965' THEN STMFSGSTRATE
								WHEN '9966' THEN STMFIGSTRATE ELSE RATE END
					FROM	TBL_ACC_INV_STAX_RATE 
					WHERE	STCODE = CHRG1.INV_TAXABLE 
							AND @INVDATE BETWEEN FROMDATE AND ISNULL(TODATE, GETDATE()) 
							AND CMPCODE = SUBSTRING(@INV_NO,1, 2) 
							AND CITYCODE= SUBSTRING(@INV_NO, 3, 3)), 0)AS RATE,    
			ISNULL((SELECT SNAME  FROM TBL_ACC_INV_STAX WHERE LTRIM(RTRIM(EDUCHRGCODE)) =  LTRIM(RTRIM(INVCHRG.INV_CHRGCODE))), '') AS DESC1,
			SBC_CHRGCODE=ISNULL((SELECT SBCCHRGCODE  FROM TBL_ACC_INV_STAX WHERE LTRIM(RTRIM(CHRGCODE)) =  LTRIM(RTRIM(INVCHRG.INV_CHRGCODE))), ''),         
			KKC_CHRGCODE=ISNULL((SELECT KKCCHRGCODE  FROM TBL_ACC_INV_STAX WHERE LTRIM(RTRIM(CHRGCODE)) =  LTRIM(RTRIM(INVCHRG.INV_CHRGCODE))), '')
			              
			--(SELECT RATE FROM TBL_ACC_INV_STAX_RATE WHERE STCODE = #TINVCHARGE1.INV_TAXABLE AND @INVDATE BETWEEN FROMDATE AND ISNULL(TODATE, GETDATE()))AS RATE    
	FROM	ACC_INVCHARGE INVCHRG
			LEFT OUTER JOIN TBL_ACC_INV_STAX STAX ON  STAX.ACCTCODE = INVCHRG.INV_ACCOUNT 
			LEFT OUTER JOIN #TINVCHARGE1 CHRG1 ON CHRG1.CHRGCODE = INVCHRG.INV_CHRGCODE  
			LEFT OUTER JOIN ACC_CHARGEMASTER CHRGMST ON CHRGMST.CHRG_CODE = INVCHRG.INV_CHRGCODE  
			LEFT OUTER JOIN CUR_MASTER ON CUR_MASTER.CUR_CODE= INVCHRG.INV_CURRENCY 
	WHERE	INVCHRG.INV_NO = @INV_NO 
			AND  INVCHRG.INV_TAXABLE IS NULL 
			AND  INVCHRG.INV_CHRGCODE  <> '9999'    
	ORDER BY INVCHRG.INV_CHRGCODE   

	--SELECT  A.INV_CHRGCODE,TOTINV_AMOUNT=B.TOTINV_AMOUNT, TOTINV_INRAMOUNT=B.TOTINV_INRAMT	
	UPDATE	A SET    
			A.TOTINV_AMOUNT=B.TOTINV_AMOUNT,
			A.TOTINV_INRAMT=B.TOTINV_INRAMT	
	FROM  #PRINT_INVCHARGE1 A INNER JOIN 
			( SELECT TOTINV_AMOUNT,TOTINV_INRAMT,INV_CHRGCODE ,SBC_CHRGCODE
			  FROM #PRINT_INVCHARGE1 INNER JOIN TBL_ACC_INV_STAX ON INV_CHRGCODE=CHRGCODE 
			) B ON A.INV_CHRGCODE=B.SBC_CHRGCODE 
	
	UPDATE	A SET    
			A.TOTINV_AMOUNT=B.TOTINV_AMOUNT,
			A.TOTINV_INRAMT=B.TOTINV_INRAMT	
	FROM	#PRINT_INVCHARGE1 A INNER JOIN 
			( SELECT TOTINV_AMOUNT,TOTINV_INRAMT,INV_CHRGCODE ,KKC_CHRGCODE
			  FROM #PRINT_INVCHARGE1 INNER JOIN TBL_ACC_INV_STAX ON INV_CHRGCODE=CHRGCODE 
			) B ON A.INV_CHRGCODE=B.KKC_CHRGCODE		

	SELECT	INV_CHRGCODE,
			INV_DESC,
			INV_AMOUNT,
			INV_INRAMT,
			TAXABLEAMT,
			TAXABLEAMTINR,
			SNAME,
			TOTINV_AMOUNT,
			TOTINV_INRAMT,
			RATE,
			DESC1= SNAME +' @ ' + INV_DESC + ' % ON '+ CONVERT(VARCHAR,TOTINV_INRAMT)
	FROM	#PRINT_INVCHARGE1

	SELECT  SUM(CONVERT(DECIMAL(15, 2), ISNULL( INV_AMOUNT, 0))) AS TOTALTAXABLEAMT, 
			SUM(CONVERT(DECIMAL(15, 2), ISNULL(INV_INRAMT, 0)))  AS TOTALTAXABLEAMTINR 
	FROM	ACC_INVCHARGE 
	WHERE	ACC_INVCHARGE.INV_NO = @INV_NO 
			AND  INV_TAXABLE IS NULL    
END    
ELSE    
BEGIN    

	/*if exists(select inv_chrgcode from acc_invcharge where inv_no = @inv_no and inv_taxable<>'N' union select inv_chrgcode from acc_invcharge1 where inv_no = @inv_no and inv_taxable <>'N')    
	begin    
	select inv_chrgcode, inv_desc , inv_amount, inv_inramt, SName from acc_invcharge     
	left outer Join tbl_Acc_Inv_STax on  tbl_Acc_Inv_STax.Acctcode = acc_invcharge.inv_account    
	where acc_invcharge.inv_no = @inv_no and   inv_taxable IS NULL    

	select  sum(convert(decimal(15, 2), inv_amount)) as TotalTaxableAmt, sum(convert(decimal(15, 2), inv_inramt))  as TotalTaxableAmtINR from acc_invcharge where acc_invcharge.inv_no = @inv_no and  inv_taxable is null    
	end*/    

	--select '' as inv_chrgcode, '' AS inv_desc,   '' AS inv_amount, '' AS inv_inramt, '' AS SName, '' AS Totinv_amount,  '' AS Totinv_inramt, '' AS Rate      
	INSERT INTO #PRINT_INVCHARGE1	
	SELECT	INVCHRG.INV_CHRGCODE, 
			INVCHRG.INV_DESC , 
			CONVERT(DECIMAL(15,2),INVCHRG.INV_AMOUNT) AS INV_AMOUNT,     
			CONVERT(DECIMAL(15,2), INVCHRG.INV_INRAMT) AS INV_INRAMT, 
			CONVERT(DECIMAL(15,2), INVCHRG.TAXABLEAMT) AS TAXABLEAMT,     
			CONVERT(DECIMAL(15,2), INVCHRG.TAXABLEAMTINR) AS TAXABLEAMTINR,    
			SNAME,    
			INVCHRG.INV_AMOUNT AS TOTINV_AMOUNT,
			INVCHRG.INV_INRAMT AS TOTINV_INRAMT, 
			ISNULL((SELECT  CASE INV_CHRGCODE WHEN '9961' THEN CGSTRATE
								WHEN '9962' THEN SGSTRATE
								WHEN '9963' THEN IGSTRATE
								WHEN '9964' THEN STMFCGSTRATE
								WHEN '9965' THEN STMFSGSTRATE
								WHEN '9966' THEN STMFIGSTRATE ELSE RATE END
					FROM	TBL_ACC_INV_STAX_RATE 
					WHERE	STCODE = CHRG1.INV_TAXABLE 
							AND @INVDATE BETWEEN FROMDATE AND ISNULL(TODATE, GETDATE()) 
							AND CMPCODE = SUBSTRING(@INV_NO,1, 2) 
							AND CITYCODE= SUBSTRING(@INV_NO, 3, 3)), 0)AS RATE,
			--(SELECT RATE FROM TBL_ACC_INV_STAX_RATE WHERE STCODE = #TINVCHARGE1.INV_TAXABLE AND @INVDATE BETWEEN FROMDATE AND ISNULL(TODATE, GETDATE()))AS RATE    
			ISNULL((SELECT SNAME  FROM TBL_ACC_INV_STAX WHERE LTRIM(RTRIM(EDUCHRGCODE)) =  LTRIM(RTRIM(INVCHRG.INV_CHRGCODE))), '') AS DESC1,
			SBC_CHRGCODE=ISNULL((SELECT SBCCHRGCODE  FROM TBL_ACC_INV_STAX WHERE LTRIM(RTRIM(CHRGCODE)) =  LTRIM(RTRIM(INVCHRG.INV_CHRGCODE))), ''),         
			KKC_CHRGCODE=ISNULL((SELECT KKCCHRGCODE  FROM TBL_ACC_INV_STAX WHERE LTRIM(RTRIM(CHRGCODE)) =  LTRIM(RTRIM(INVCHRG.INV_CHRGCODE))), '')
	FROM	ACC_INVCHARGE INVCHRG
			LEFT OUTER JOIN TBL_ACC_INV_STAX STAX ON  STAX.ACCTCODE = INVCHRG.INV_ACCOUNT 
			LEFT OUTER JOIN #TINVCHARGE1 CHRG1 ON CHRG1.CHRGCODE = INVCHRG.INV_CHRGCODE    
	WHERE	INVCHRG.INV_NO = @INV_NO 
			AND  INVCHRG.INV_TAXABLE IS NULL 
			AND INVCHRG.ID = 0    

	SELECT	INV_CHRGCODE,
			INV_DESC,
			INV_AMOUNT,
			INV_INRAMT,
			TAXABLEAMT,
			TAXABLEAMTINR,
			SNAME,
			TOTINV_AMOUNT,
			TOTINV_INRAMT,
			RATE,
			DESC1 = SNAME +' @ ' + INV_DESC + ' % ON '+ CONVERT(VARCHAR,TOTINV_INRAMT)
			
	FROM	#PRINT_INVCHARGE1
	
	SELECT	SUM(CONVERT(DECIMAL(15, 2), INV_AMOUNT)) AS TOTALTAXABLEAMT, 
			SUM(CONVERT(DECIMAL(15, 2), INV_INRAMT))  AS TOTALTAXABLEAMTINR 
	FROM	ACC_INVCHARGE 
	WHERE	ACC_INVCHARGE.INV_NO = @INV_NO 
			AND  INV_TAXABLE IS NULL 
			AND ACC_INVCHARGE.ID = 0    
END    
    
    
 /*if object_id('tempdb..#TEMPCHARGE1') is not null    
  drop table #TEMPCHARGE1     
 if object_id('tempdb..#TEMPCHARGE2') is not null    
  drop table #TEMPCHARGE2     
    
 SELECT  acc_invcharge1.inv_taxable, SUM(convert(float, inv_amount)) AS inv_amount, SUM(convert(float, inv_inramt)) AS inv_inramt, SUM(acc_invcharge1.TaxableAmt) AS TaxableAmt, SUM(acc_invcharge1.TaxableAmtINR) AS TaxableAmtINR,     
    tbl_Acc_Inv_STax.SName, tbl_Acc_Inv_STax_CmpCity.percentage INTO #TEMPCHARGE1    
 FROM     acc_invcharge1     
    LEFT OUTER JOIN tbl_Acc_Inv_STax_CmpCity ON tbl_Acc_Inv_STax_CmpCity.Code = acc_invcharge1.inv_taxable    
    LEFT OUTER JOIN tbl_Acc_Inv_STax ON tbl_Acc_Inv_STax.Code = acc_invcharge1.inv_taxable    
 WHERE  inv_no = @inv_no AND tbl_Acc_Inv_STax_CmpCity.cmpcode = SUBSTRING(@inv_no , 1, 2)     
    AND tbl_Acc_Inv_STax_CmpCity.citycode = SUBSTRING(@inv_no , 3, 3)     
 GROUP BY acc_invcharge1.inv_taxable,  tbl_Acc_Inv_STax.SName, tbl_Acc_Inv_STax_CmpCity.percentage    
     
 SELECT * FROM #TEMPCHARGE1    
    
 SELECT ((inv_amount * percentage)/100) AS TotTaxableAmt, ((inv_inramt * percentage)/100) AS TotTaxableAmtINR INTO #TEMPCHARGE2    
 FROM #TEMPCHARGE1    
     
 SELECT * FROM #TEMPCHARGE2    
    
 SELECT  SUM(TotTaxableAmt) AS TotalTaxableAmt , SUM(TotTaxableAmt) AS TotalTaxableAmtINR    
 FROM #TEMPCHARGE2*/    
     
    
	IF OBJECT_ID('TEMPDB..#INVCHARGE') IS NOT NULL    
	DROP TABLE #INVCHARGE    
	 
	IF OBJECT_ID('TEMPDB..#INVCHARGE1') IS NOT NULL    
	DROP TABLE #INVCHARGE1        

	CREATE TABLE #INVCHARGE    
	(    
		INV_AMOUNT DECIMAL(15,2),    
		INV_INRAMT DECIMAL(15,2),    
		INV_TAXABLE VARCHAR(1)    
	)    

	INSERT INTO #INVCHARGE    
	SELECT	CASE WHEN INV_AMOUNT = '' THEN 0 ELSE CONVERT(DECIMAL(15,2), INV_AMOUNT) END AS INV_AMOUNT,    
			CASE WHEN INV_INRAMT = '' THEN 0 ELSE CONVERT(DECIMAL(15, 2), INV_INRAMT) END AS INV_INRAMT,    
			-- INV_AMOUNT,    
			--INV_INRAMT,     
			INV_TAXABLE    
	FROM    ACC_INVCHARGE    
	WHERE	INV_NO = @INV_NO AND RTRIM(INV_TAXABLE) <> 'N'    

	INSERT INTO #INVCHARGE    
	SELECT	CASE WHEN INV_AMOUNT = '' THEN 0 ELSE CONVERT(DECIMAL(15,2), INV_AMOUNT) END AS INV_AMOUNT,    
			CASE WHEN INV_INRAMT = '' THEN 0 ELSE CONVERT(DECIMAL(15, 2), INV_INRAMT) END AS INV_INRAMT,    
			-- INV_AMOUNT,    
			--INV_INRAMT,     
			INV_TAXABLE    
	FROM    ACC_INVCHARGE1    
	WHERE	INV_NO = @INV_NO 
			AND RTRIM(INV_TAXABLE) <> 'N'    

	SELECT	SUM(CONVERT(DECIMAL(15,2), ISNULL(INV_AMOUNT, 0))) AS INV_AMOUNT,    
			SUM(CONVERT(DECIMAL(15,2), ISNULL(INV_INRAMT, 0))) AS INV_INRAMT,    
			INV_TAXABLE 
	INTO	#INVCHARGE1    
	FROM    #INVCHARGE     
	GROUP BY INV_TAXABLE    

	IF EXISTS(SELECT INV_AMOUNT AS ROUNDVALUE FROM ACC_INVCHARGE WHERE INV_CHRGCODE  = '9999' AND  INV_NO = @INV_NO)    
	BEGIN    
		SELECT	CONVERT(DECIMAL(15,2), INV_AMOUNT) AS ROUNDVALUE 
		FROM	ACC_INVCHARGE 
		WHERE	INV_CHRGCODE  = '9999' AND  INV_NO = @INV_NO    
	END    
	ELSE    
	BEGIN    
		SELECT ' ' AS ROUNDVALUE    
	END    

	/*Table no 10 QR Code*/
	SELECT	ISNULL(QRCODE,'') QRCODE,
			ISNULL(IRNNO,'') IRNNO,
			/* === ADDED 18-07-2026 : e-invoice acknowledgement for the new TAX INVOICE print === */
			ISNULL(ACKNO,'') ACKNO,
			ISNULL(ACKDATE,'') ACKDATE
	FROM	ACC_INVOICE_EINV_GSTIRN 
	WHERE INV_NO= @INV_NO
	/*******************/

	DECLARE @JOBNO VARCHAR(30)

	SET @JOBNO=(SELECT top 1 INV_JOBNO FROM acc_invjobno
				INNER JOIN acc_invoice ON acc_invoice.INV_NO=acc_invjobno.INV_NO
				WHERE acc_invoice.INV_NO=@INV_NO)

	IF(SUBSTRING(@JOBNO,8,1) =1 OR SUBSTRING(@JOBNO,8,1) =2)
	BEGIN
			SELECT (EXPT_MASTER.EXPT_SHIPBILLNO +' / ' + EXPT_MASTER.EXPT_SHIPBILLDT)  BILLNO,CITY_MASTER.CITY_NAME POL,
			CITY.CITY_NAME POD,'EXPORT' INVTYPE FROM ACC_INVJOBNO 
			INNER JOIN EXPT_MASTER ON EXPT_MASTER.EXPTNO=ACC_INVJOBNO.INV_JOBNO 
			LEFT OUTER JOIN CITY_MASTER ON  CITY_MASTER.CITY_CODE=EXPT_MASTER.VSL_PORT
			LEFT OUTER  JOIN CITY_MASTER CITY ON CITY.CITY_CODE=EXPT_MASTER.EXPT_POD
			WHERE INV_NO = @INV_NO  
	END
	ELSE IF (SUBSTRING(@JOBNO,8,1) =5 OR SUBSTRING(@JOBNO,8,1) =6)
	BEGIN
			SELECT TBL_IMP_IMPORT.BILL_ENTRYNO BILLNO, CITY_MASTER.CITY_NAME POL, VSL_ARRIVALPORTPOD POD, 'IMPORT' INVTYPE FROM ACC_INVJOBNO 
			INNER JOIN TBL_IMP_IMPORT ON TBL_IMP_IMPORT.IMPORT_CODE=ACC_INVJOBNO.INV_JOBNO  
			LEFT OUTER  JOIN CITY_MASTER ON  CITY_MASTER.CITY_CODE=TBL_IMP_IMPORT.FK_SHIPMENTPORT
			--LEFT OUTER  JOIN  CITY_MASTER CITY ON CITY.CITY_CODE=TBL_IMP_IMPORT.FK_ARRIVALPORT
			WHERE INV_NO = @INV_NO
	END
	ELSE IF (SUBSTRING(@JOBNO,8,1) <>5 OR SUBSTRING(@JOBNO,8,1) <> 6 OR SUBSTRING(@JOBNO,8,1) <>1 OR SUBSTRING(@JOBNO,8,1) <> 2)
	BEGIN
		SELECT '' BILLNO , '' POL ,'' POD, 'MISC'  INVTYPE

	END

    
	--SELECT EXPT_MASTER.EXPT_SHIPBILLNO,VSL_PORT,EXPT_POD FROM ACC_INVJOBNO 
	--INNER JOIN EXPT_MASTER ON EXPT_MASTER.EXPTNO=ACC_INVJOBNO.INV_JOBNO WHERE INV_NO = @INV_NO ORDER BY ACC_INVJOBNO.ID  


	DECLARE @CUR_SNAME VARCHAR(20)
	SET @CUR_SNAME=
	(SELECT CUR_SNAME	FROM  CUR_MASTER 
			INNER JOIN ACC_INVOICE ACCINV ON CUR_MASTER.CUR_CODE = ACCINV.INV_CUR 
		WHERE ACCINV.INV_NO = @INV_NO)
	
	

	if @cmp_code='30'
	BEGIN
		SELECT	CUR_SNAME,
				'LINKS CARGO AGENCIES PVT LTD'  BENEFICIARY,
				'SCBLINBBXXX' SWIFTCODE, 
				'U6301MH1993PTC074742'  CINNO1,
				'STANDARD CHARTERED BANK' BANKNAME,
				'AAACL2771L' PANNO,
				'FORT' BRANCH,
				'SCBL0036001' RTGSCODE,
				'90,M.G.ROAD,MUMBAI PIN : 400001' BANKADDRESS,
				'400036010' MICRCODE,
				'INDIA' COUNTRY,
				'SCBL0036001' IFSCCODE, 
				BANKACT = (CASE WHEN @INVCLIENT='E100388' THEN '231-0-500350-0' 
							ELSE
								CASE WHEN CUR_SNAME='INR' THEN '231-0-500350-0' ELSE '231-0-506328-7' END
							END
							)
				,UAMNO='MH18E0083119'
		FROM	CUR_MASTER 
				INNER JOIN ACC_INVOICE ACCINV ON CUR_MASTER.CUR_CODE = ACCINV.INV_CUR 
		WHERE	ACCINV.INV_NO = @INV_NO
	END
	ELSE IF @cmp_code='32'
	BEGIN
		SELECT	CUR_SNAME,
				'OCEAN LINKS SHIPPING  PVT LTD'  BENEFICIARY,
				'SCBLINBBXXX' SWIFTCODE, 
				'U63090MH1997PTC110957'  CINNO1,
				'STANDARD CHARTERED BANK' BANKNAME,
				'AAACO1629A' PANNO,
				'FORT' BRANCH,
				'SCBL0036001' RTGSCODE,
				'90,M.G.ROAD,MUMBAI PIN : 400001' BANKADDRESS,
				'400036010' MICRCODE,
				'INDIA' COUNTRY,
				'SCBL0036001' IFSCCODE, 
				BANKACT = (CASE WHEN @INVCLIENT='E100388' THEN '231-0-500426-4' 
							ELSE
								CASE WHEN CUR_SNAME='INR' THEN '231-0-500426-4' ELSE '231-0-506328-7' END
							END
							)
				,UAMNO=''
		FROM	CUR_MASTER 
				INNER JOIN ACC_INVOICE ACCINV ON CUR_MASTER.CUR_CODE = ACCINV.INV_CUR 
		WHERE	ACCINV.INV_NO = @INV_NO
	END

	--SELECT ISNULL(QRCODE,'') QRCODE,ISNULL(IRNNO,'') IRNNO FROM ACC_INVOICE_EINV_GSTIRN WHERE INV_NO= @INV_NO

--SELECT 'Regd. Office : ' + CMP_ADD1 + CMP_ADD2 + CMP_ADD3 + ', GSTIN - ' + GSTIN AS CMPADDRESS FROM CMP_ADDRESS
--WHERE CMP_ADDRESS.CMP_CODE =@cmp_code AND  CMP_ADDRESS.CMP_CITY = @CITY_CODE
--IF @@ERROR != 0    
--  RETURN @@ERROR    
-- ELSE    
--  RETURN 0  


  








GO
