USE [LinksDB20]
GO
/*
CREATED ON --21.11.2009
*/
ALTER PROC [dbo].[USP_ACC_BRBPCRCPCE_PAYORDER_GENERATE_NG]
--DECLARE 
@CMPID AS VARCHAR(4),
@CMP_CODE VARCHAR(20),
@CITY_CODE VARCHAR(20),
@OURBANK VARCHAR(20),
@BPREQNO VARCHAR(3000),
@MAKERID VARCHAR(50),
@MAKERIP VARCHAR(20)

AS
/*
SET @CMPID = '1885' 
SET @CMP_CODE = '01' 
SET @CITY_CODE = '101' 
SET @OURBANK='G100286' 
SET @BPREQNO = '01101220412R013|436546547,' 
SET @MAKERID = '1885 ' 
SET @MAKERIP = '127.0.0.1'
--*/

----START

BEGIN
	DECLARE @CURDATE AS VARCHAR(25)
	SET @CURDATE=(SELECT CONVERT(DATETIME,GETDATE(),101))

	DECLARE @CURCHQPRINTDATE VARCHAR(25)
	SET @CURCHQPRINTDATE=(SELECT REPLACE(CONVERT(VARCHAR,GETDATE(),105),'-','/'))

	DECLARE @TEMPREC VARCHAR(200)
	DECLARE @TEMPRECINDEX INT

	DECLARE @TEMPFIELD VARCHAR(200)
	DECLARE @TEMPFIELDINDEX INT
	
	--SET @BPREQNO=@BPREQNO+';'

	DECLARE @SQLVALUE VARCHAR(200)
	DECLARE @SQLVALUEQ VARCHAR(200)
	SET @SQLVALUE=''
	SET @SQLVALUEQ=''

	declare @cnt int,@cntr int

IF OBJECT_ID('TEMPDB..#TEMP_REQCHQNO') IS NOT NULL
DROP TABLE #TEMP_REQCHQNO

CREATE TABLE #TEMP_REQCHQNO                        
(                          
	PK_ID INT IDENTITY,                          
	ENTRYNO_BNKREF  VARCHAR(60)
)

IF OBJECT_ID('TEMPDB..#ENTRYNO') IS NOT NULL
DROP TABLE #ENTRYNO

CREATE TABLE #ENTRYNO                        
(                          
	ID INT IDENTITY,                          
	ENTRYNO VARCHAR(30),
	BNKREF  VARCHAR(30)
)

INSERT INTO #TEMP_REQCHQNO
SELECT [VALUE] FROM DBO.FN_SPLIT( @BPREQNO,',') WHERE [VALUE]<>''


SELECT @CNT = COUNT(*) FROM #TEMP_REQCHQNO
SET @cntr=1

IF @CNT>1
BEGIN
	WHILE @cntr <= @CNT
	BEGIN
		DECLARE @ENTRYNO_BNKREF VARCHAR(60),@BPREQ NVARCHAR(15), @BANKREFNO NVARCHAR(30)
		SET @ENTRYNO_BNKREF='' 

		SELECT @ENTRYNO_BNKREF=ENTRYNO_BNKREF FROM #TEMP_REQCHQNO WHERE PK_ID = @cntr

		SELECT @BPREQ=VALUE FROM DBO.FN_SPLIT(@ENTRYNO_BNKREF,'|') WHERE [VALUE]<>'' AND IDX=0
		SELECT @BANKREFNO=VALUE FROM DBO.FN_SPLIT(@ENTRYNO_BNKREF,'|') WHERE [VALUE]<>'' AND IDX=1 
		
		INSERT INTO #ENTRYNO
		SELECT BPREQ=@BPREQ, BANKREFNO=@BANKREFNO

		SET @CNTR=@CNTR+1
	END	
END
ELSE
BEGIN
	SELECT @ENTRYNO_BNKREF=ENTRYNO_BNKREF FROM #TEMP_REQCHQNO WHERE PK_ID = @cntr

	SELECT @BPREQ=VALUE FROM DBO.FN_SPLIT(@ENTRYNO_BNKREF,'|') WHERE [VALUE]<>'' AND IDX=0
	SELECT @BANKREFNO=VALUE FROM DBO.FN_SPLIT(@ENTRYNO_BNKREF,'|') WHERE [VALUE]<>'' AND IDX=1 

	INSERT INTO #ENTRYNO
	SELECT BPREQ=@BPREQ, BANKREFNO=@BANKREFNO
END

--SELECT * FROM #ENTRYNO

	--WHILE LEN(@BPREQNO)>0
	--BEGIN
	--	SET @TEMPRECINDEX = CHARINDEX(';', @BPREQNO) 
	--	SET @TEMPREC = SUBSTRING(@BPREQNO, 1, (@TEMPRECINDEX - 1)) 
	--	PRINT @TEMPREC
	--	SET @SQLVALUE=''
	--	WHILE LEN(@TEMPREC)>0
	--	BEGIN
	--		SET @TEMPFIELDINDEX = CHARINDEX(',', @TEMPREC) 
	--		SET @TEMPFIELD = SUBSTRING(@TEMPREC, 1, (@TEMPFIELDINDEX - 1)) 
	--		--PRINT @TEMPFIELD
	--		SET @SQLVALUE = ''''+@TEMPFIELD+''','
	--		--PRINT 'INSERT INTO #ENTRYNO VALUES('+SUBSTRING(@SQLVALUE, 0, LEN(@SQLVALUE))+')'
	--		SET @SQLVALUEQ = 'INSERT INTO #ENTRYNO VALUES('+SUBSTRING(@SQLVALUE, 0, LEN(@SQLVALUE))+')'
	--		EXECUTE(@SQLVALUEQ)
	--		SET @TEMPREC = SUBSTRING(@TEMPREC, (@TEMPFIELDINDEX + 1), (LEN(@TEMPREC) - @TEMPFIELDINDEX))
	--	END
	--	SET @BPREQNO = SUBSTRING(@BPREQNO, (@TEMPRECINDEX + 1), (LEN(@BPREQNO) - @TEMPRECINDEX))
	--END
	--SELECT * FROM #ENTRYNO


	--/*
	DECLARE @I INT
	SET @I=0
	DECLARE @SUCCESSENTRY VARCHAR(2000)
	DECLARE @NSUCCESSENTRY VARCHAR(2000)
	DECLARE @PRINTCOUNT INT 

	DECLARE @CUR_ENTRYNO VARCHAR(20)
	DECLARE @CHEQUENO VARCHAR(20)
	DECLARE @OURBANK1 VARCHAR(20)
	DECLARE @STATUS VARCHAR(20)
	DECLARE @REMARKS VARCHAR(20)
	DECLARE @AVAILCOUNT INT
	DECLARE @CUR_BANKREFNO VARCHAR(30)
	SET @AVAILCOUNT=0
	SET @SUCCESSENTRY =''
	SET @NSUCCESSENTRY =''

	SET @PRINTCOUNT= (SELECT COUNT(ID) FROM #ENTRYNO)

	WHILE(@I<=@PRINTCOUNT)
	BEGIN
		SELECT	@CUR_ENTRYNO = ENTRYNO ,
				@CUR_BANKREFNO = BNKREF 				
		FROM	#ENTRYNO 
		WHERE	ID=@I

		--SELECT @CUR_BANKREFNO=BNKREF FROM #ENTRYNO WHERE ID=@I

		IF EXISTS(SELECT ENTRYNO FROM ACC_BANK_CMP WHERE CMPCODE=@CMP_CODE  AND OURBANK=@OURBANK AND ENTRYNO=@CUR_ENTRYNO
					AND ISNULL(CHKPRINTAUTHORITY,0)=1) --<< FIX: only generate BP for AUTHORISED requests
		BEGIN
			SET @AVAILCOUNT=@AVAILCOUNT+1
			DECLARE @PRECODE AS VARCHAR(15)    
			DECLARE @TEMPSQL AS NVARCHAR(1000)    
			DECLARE @LASTCODE AS VARCHAR(15)    
			DECLARE @INTCNT AS INT    
			DECLARE @RIGHTNUM AS VARCHAR(10)    
			DECLARE @ENTRYDT AS VARCHAR(20)
			DECLARE @ENTRYNO AS VARCHAR(20)
			DECLARE @VOUCHERTYPE AS VARCHAR(1)    
			SET @VOUCHERTYPE = '2'    
			SET @ENTRYDT=CONVERT(VARCHAR,GETDATE(),103)
			SET @PRECODE = @CMP_CODE + @CITY_CODE +  SUBSTRING(@ENTRYDT, 9, 2) + SUBSTRING(@ENTRYDT, 4, 2) + SUBSTRING(@ENTRYDT, 1, 2)  + @VOUCHERTYPE  
			
			SET @LASTCODE = @ENTRYNO
			
			EXEC [DBO].[USP_ACC_BRBPCRCPCE_INSERT_CODE] 'BP',@PRECODE,  @ENTRYNO OUTPUT
			
			--CREATE TABLE #2(CODE VARCHAR(15))    
			--SET @TEMPSQL = 'INSERT INTO #2 SELECT MAX(ENTRYNO) FROM ACC_BANK WHERE LEFT(ENTRYNO,12) = ' + CHAR(39) + @PRECODE + CHAR(39)    
			--EXEC(@TEMPSQL)    
			--SET @LASTCODE = (SELECT TOP 1  CODE FROM #2)    
			--DROP TABLE #2
		
			--IF (@LASTCODE IS NULL)    
			--BEGIN    
			--	SET @RIGHTNUM = '001'    
			--	SET @LASTCODE = @PRECODE + @RIGHTNUM    
			--	SET @ENTRYNO = @LASTCODE    
			--END    
			--ELSE    
			--BEGIN    
			--	SET @RIGHTNUM = RIGHT(@LASTCODE,3)    
			--	SET @RIGHTNUM = CONVERT(NUMERIC, @RIGHTNUM) + 1    
			--	WHILE(LEN(@RIGHTNUM) < 3)    
			--	BEGIN    
			--		SET  @RIGHTNUM = '0' +  @RIGHTNUM    
			--	END    
			--	SET @LASTCODE = @PRECODE + @RIGHTNUM    
			--	SET @ENTRYNO = @LASTCODE    
			--END

			
			--BEGIN TRANSACTION----------------------START
			IF EXISTS(SELECT ENTRYNO FROM ACC_BANK_CMP WHERE ENTRYNO=@CUR_ENTRYNO AND ACC_BANK_ENTRYNO IS NULL OR ACC_BANK_ENTRYNO='')
			BEGIN
				--SELECT 'TRUE'
				INSERT INTO ACC_BANK 
						(	ENTRYNO,
							ENTRYDT,
							STATUS,
							BANK,
							CHEQUETYPE,
							CHEQUENO,
							CHEQUEDT,
							OURBANK,
							NARRATION1,
							NARRATION2,
							CITYCODE,
							CMPCODE,
							ENTMM,
							ENTYR,
							ENTDD,
							ENTNO,
							EXPENSE,
							USERNAME,
							CMPID,
							ACTUALAMOUNT,
							NARRATION,
							ADVAMT,
							AMTWITHOUTADV,
							CLEARANCEDATE,
							COMPUTERISEDCHEQUE,
							PAYEENAME,
							NOTOVERFLAG,
							BANKREFNO )

					SELECT	@ENTRYNO,
							@ENTRYDT,
							'BP',
							BANK,
							CHEQUETYPE,
							CHEQUENO,
							@CURCHQPRINTDATE,--CHEQUEDT,
							OURBANK,
							NARRATION1,
							NARRATION2,
							CITYCODE,
							CMPCODE,
							ENTMM,
							ENTYR,
							ENTDD,
							ENTNO,
							EXPENSE,
							USERNAME,
							@CMPID,
							ACTUALAMOUNT,
							NARRATION,
							ADVAMT,
							AMTWITHOUTADV,
							CLEARANCEDATE,
							COMPUTERISEDCHEQUE,
							PAYEENAME,
							NOTOVERFLAG,
							@CUR_BANKREFNO
					FROM	ACC_BANK_CMP 
					WHERE	ENTRYNO=@CUR_ENTRYNO


				DECLARE @COLUMNNAME NVARCHAR(4000)
				DECLARE @ORIGINALDATA NVARCHAR(4000)
				DECLARE @PKID VARCHAR(10)
				DECLARE @FK_TRACKID VARCHAR(10)
				SET @COLUMNNAME =''
				SET @ORIGINALDATA =''
				SET @PKID=''
				
				SET @COLUMNNAME='ID|ENTRYNO|ENTRYDT|STATUS|BANK|CHEQUETYPE|CHEQUENO|CHEQUEDT|OURBANK|NARRATION1|NARRATION2|CITYCODE|CMPCODE|ENTMM|ENTYR|ENTDD|ENTNO|EXPENSE|USERNAME|CMPID|ACTUALAMOUNT|NARRATION|ADVAMT|AMTWITHOUTADV|CLEARANCEDATE|COMPUTERISEDCHEQUE|PAYEENAME|NOTOVERFLAG'
				SELECT @ORIGINALDATA =	CONVERT(VARCHAR,ISNULL(ID,''))+'|'+
										CONVERT(VARCHAR,ISNULL(@ENTRYNO,''))+'|'+
										ISNULL(@ENTRYDT,'')+'|BP|'+
										ISNULL(BANK,'')+'|'+
										ISNULL(CHEQUETYPE,'')+'|'+
										CONVERT(VARCHAR,ISNULL(CHEQUENO,''))+'|'+
										ISNULL(CHEQUEDT,'')+'|'+ISNULL(OURBANK,'')+'|'+
										ISNULL(NARRATION1,'')+'|'+ISNULL(NARRATION2,'')+'|'+
										CONVERT(VARCHAR,ISNULL(CITYCODE,''))+'|'+
										CONVERT(VARCHAR,ISNULL(CMPCODE,''))+'|'+
										CONVERT(VARCHAR,ISNULL(ENTMM,''))+'|'+
										CONVERT(VARCHAR,ISNULL(ENTYR,''))+'|'+CONVERT(VARCHAR,ISNULL(ENTDD,''))+'|'+CONVERT(VARCHAR,ISNULL(ENTNO,''))+'|'+CONVERT(VARCHAR,ISNULL(EXPENSE,''))+'|'+ISNULL(USERNAME,'')+'|'+
										CONVERT(VARCHAR,ISNULL(@CMPID,''))+'|'+CONVERT(VARCHAR,ISNULL(ACTUALAMOUNT,'0'))+'|'+ISNULL(NARRATION,'')+'|'+CONVERT(VARCHAR,ISNULL(ADVAMT,'0'))+'|'+CONVERT(VARCHAR,ISNULL(AMTWITHOUTADV,'0'))+'|'+
										CONVERT(VARCHAR,ISNULL(CLEARANCEDATE,''))+'|'+CONVERT(VARCHAR,ISNULL(COMPUTERISEDCHEQUE,'0'))+'|'+ISNULL(PAYEENAME,'')+'|'+ISNULL(NOTOVERFLAG,''),
					   @PKID=CONVERT(VARCHAR,ISNULL(ID,'0'))
				FROM ACC_BANK 
				WHERE ENTRYNO=@ENTRYNO

				INSERT INTO TBL_USERTRACK
							VALUES(
							@CMPID,
							GETDATE(),
							'ADD',
							'ACC_BANK',
							@COLUMNNAME,
							@ORIGINALDATA,
							'',
							@PKID,
							@ENTRYNO,
							@MAKERIP,
							@MAKERIP)

				SET @FK_TRACKID= CONVERT(VARCHAR,@@IDENTITY)
				
				INSERT INTO  ACC_BANKDTLS 
				(	ENTRYNO,CLIENT,JOBNO,BILLNO,DEDUCTION,AMOUNT,
					ENTRYTYPE,EMP_CODE, USERNAME, NARRATION,ITEMCODE,DeptId ,
					IS_GST,ISTDSCALC,IS_TDS,TDS_TYPE,RATE,TDS_AMT,GSTRATE
				 )
				SELECT	@ENTRYNO, CLIENT,	JOBNO, BILLNO, DEDUCTION, AMOUNT, 
						ENTRYTYPE, EMP_CODE, USERNAME,NARRATION ,ITEMCODE, DEPTID,
						IS_GST=ISNULL(IS_GST,'0'),ISTDSCALC=ISNULL(ISTDSCALC,'0'),
						IS_TDS=ISNULL(IS_TDS,'N'),TDS_TYPE=ISNULL(TDS_TYPE,''),
						RATE=ISNULL(RATE,0),TDS_AMT=ISNULL(TDS_AMT,0),GSTRATE=ISNULL(GSTRATE,0)
				FROM	ACC_BANKDTLS_CMP 
				WHERE	ENTRYNO=@CUR_ENTRYNO 

				INSERT INTO TBL_USERTRACK_DETAILS 
				SELECT  @FK_TRACKID,
						@CMPID,
						GETDATE(),
						'ADD',
						'ACC_BANKDTLS',
						'ID|ENTRYNO|CLIENT|JOBNO|BILLNO|DEDUCTION|AMOUNT|ENTRYTYPE|EMP_CODE| USERNAME| ITEMCODE| NARRATION',
						CONVERT(VARCHAR,ISNULL(ID,''))+'|'+CONVERT(VARCHAR,ISNULL(ENTRYNO,''))+'|'+ISNULL(CLIENT,'')+'|'+ISNULL(JOBNO,'')+'|'+ISNULL(BILLNO,'')+'|'+CONVERT(VARCHAR,ISNULL(DEDUCTION,'0'))+'|'+CONVERT(VARCHAR,ISNULL(AMOUNT,'0'))+'|'+ISNULL(ENTRYTYPE,'')+'|'+CONVERT(VARCHAR,ISNULL(EMP_CODE,''))+'|'+ISNULL( USERNAME,'')+'|'+CONVERT(VARCHAR,ISNULL( ITEMCODE,''))+'|'+ISNULL(NARRATION,''),
						'',
						@ENTRYNO,
						@MAKERIP,
						@MAKERIP
				FROM ACC_BANKDTLS
				WHERE ENTRYNO=@ENTRYNO 		

				IF @@ERROR = 0
				BEGIN
					--SELECT 'TRUE'
					UPDATE	ACC_BANK_CMP 
					SET		CHEQUENO=CHEQUENO,
							ACC_BANK_ENTRYNO=@ENTRYNO ,
							CHEQUEDT=@CURCHQPRINTDATE
					WHERE	ENTRYNO=@CUR_ENTRYNO 
							AND CMPCODE=@CMP_CODE 
							AND OURBANK=@OURBANK
				END
			END
				
			IF(@NSUCCESSENTRY IS NULL)
				SET @NSUCCESSENTRY=''
			SET @SUCCESSENTRY = @SUCCESSENTRY + @ENTRYNO + ',' --+ @CUR_ENTRYNO +','
			--IF @@ERROR != 0
			--	ROLLBACK TRANSACTION
			--ELSE
			--	COMMIT TRANSACTION
		END
		ELSE
		BEGIN
			IF(@NSUCCESSENTRY IS NULL)
				SET @NSUCCESSENTRY=''
			SET @NSUCCESSENTRY = @NSUCCESSENTRY + ISNULL(@CUR_ENTRYNO,'') + ',' --<< FIX: report BPR req no (was @ENTRYNO)
		END
		SET @I=@I+1
	END
	DROP TABLE #ENTRYNO
	SELECT '0' AS 'STATUS' ,CASE WHEN LEN(ISNULL(@SUCCESSENTRY,''))>0 THEN SUBSTRING(@SUCCESSENTRY,1,LEN(@SUCCESSENTRY)-1) ELSE '' END AS 'SUCCESS',ISNULL(@NSUCCESSENTRY,'') AS 'INVALID' --<< FIX: guard empty success list
END
GO
